/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { BodyAuthLoginGrantType } from './bodyAuthLoginGrantType';
import type { BodyAuthLoginClientId } from './bodyAuthLoginClientId';
import type { BodyAuthLoginClientSecret } from './bodyAuthLoginClientSecret';

export interface BodyAuthLogin {
  grant_type?: BodyAuthLoginGrantType;
  username: string;
  password: string;
  scope?: string;
  client_id?: BodyAuthLoginClientId;
  client_secret?: BodyAuthLoginClientSecret;
}
