/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { PropinsiResponse } from './propinsiResponse';
import type { Dati2Response } from './dati2Response';
import type { KecamatanResponse } from './kecamatanResponse';
import type { KelurahanResponse } from './kelurahanResponse';

export interface DashboardFiltersResponse {
  propinsi: PropinsiResponse[];
  dati2: Dati2Response[];
  kecamatan: KecamatanResponse[];
  kelurahan: KelurahanResponse[];
  available_years: string[];
}
