/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { DashboardStatsResponseFilteredBy } from './dashboardStatsResponseFilteredBy';
import type { DashboardStatsResponseFilterValue } from './dashboardStatsResponseFilterValue';
import type { DashboardStatsResponseYearFilter } from './dashboardStatsResponseYearFilter';

export interface DashboardStatsResponse {
  total_sppt: number;
  total_sppt_lunas: number;
  total_sppt_belum_lunas: number;
  total_pbb_terhutang: number;
  total_bangunan: number;
  total_nilai_bangunan: number;
  rata_rata_luas_bangunan: number;
  total_propinsi: number;
  total_dati2: number;
  total_kecamatan: number;
  total_kelurahan: number;
  filtered_by?: DashboardStatsResponseFilteredBy;
  filter_value?: DashboardStatsResponseFilterValue;
  year_filter?: DashboardStatsResponseYearFilter;
}
