/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */

export type DashboardGetSpptReportDataParams = {
/**
 * Filter by year (THN_PAJAK_SPPT)
 */
year?: string | null;
/**
 * Filter by kecamatan code
 */
kd_kecamatan?: string | null;
/**
 * Page number
 * @minimum 1
 */
page?: number;
/**
 * Items per page
 * @minimum 1
 * @maximum 1000
 */
limit?: number;
};
