/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */

export type DashboardGetDashboardFiltersParams = {
/**
 * Filter by province code for hierarchical loading
 */
kd_propinsi?: string | null;
/**
 * Filter by dati2 code for hierarchical loading
 */
kd_dati2?: string | null;
/**
 * Filter by kecamatan code for hierarchical loading
 */
kd_kecamatan?: string | null;
};
