/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */

export type DashboardGetDashboardStatsParams = {
/**
 * Filter by year (THN_PAJAK_SPPT)
 */
year?: string | null;
/**
 * Filter by province code
 */
kd_propinsi?: string | null;
/**
 * Filter by dati2/kabupaten code
 */
kd_dati2?: string | null;
/**
 * Filter by kecamatan code
 */
kd_kecamatan?: string | null;
/**
 * Filter by kelurahan code
 */
kd_kelurahan?: string | null;
};
