/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */

export interface Dati2Response {
  KD_PROPINSI: string;
  KD_DATI2: string;
  NM_DATI2: string;
}
