/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { DatSubjekPajakResponseNMWP } from './datSubjekPajakResponseNMWP';
import type { DatSubjekPajakResponseJALANWP } from './datSubjekPajakResponseJALANWP';
import type { DatSubjekPajakResponseBLOKKAVNOWP } from './datSubjekPajakResponseBLOKKAVNOWP';
import type { DatSubjekPajakResponseRWWP } from './datSubjekPajakResponseRWWP';
import type { DatSubjekPajakResponseRTWP } from './datSubjekPajakResponseRTWP';
import type { DatSubjekPajakResponseKELURAHANWP } from './datSubjekPajakResponseKELURAHANWP';
import type { DatSubjekPajakResponseKOTAWP } from './datSubjekPajakResponseKOTAWP';
import type { DatSubjekPajakResponseKDPOSWP } from './datSubjekPajakResponseKDPOSWP';
import type { DatSubjekPajakResponseTELPWP } from './datSubjekPajakResponseTELPWP';
import type { DatSubjekPajakResponseNPWP } from './datSubjekPajakResponseNPWP';
import type { DatSubjekPajakResponseSTATUSPEKERJAANWP } from './datSubjekPajakResponseSTATUSPEKERJAANWP';
import type { DatSubjekPajakResponseEMAILWP } from './datSubjekPajakResponseEMAILWP';

/**
 * Response model for dat_subjek_pajak data
 */
export interface DatSubjekPajakResponse {
  SUBJEK_PAJAK_ID: string;
  NM_WP?: DatSubjekPajakResponseNMWP;
  JALAN_WP?: DatSubjekPajakResponseJALANWP;
  BLOK_KAV_NO_WP?: DatSubjekPajakResponseBLOKKAVNOWP;
  RW_WP?: DatSubjekPajakResponseRWWP;
  RT_WP?: DatSubjekPajakResponseRTWP;
  KELURAHAN_WP?: DatSubjekPajakResponseKELURAHANWP;
  KOTA_WP?: DatSubjekPajakResponseKOTAWP;
  KD_POS_WP?: DatSubjekPajakResponseKDPOSWP;
  TELP_WP?: DatSubjekPajakResponseTELPWP;
  NPWP?: DatSubjekPajakResponseNPWP;
  STATUS_PEKERJAAN_WP?: DatSubjekPajakResponseSTATUSPEKERJAANWP;
  EMAIL_WP?: DatSubjekPajakResponseEMAILWP;
}
