/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { KelurahanResponseNOKELURAHAN } from './kelurahanResponseNOKELURAHAN';
import type { KelurahanResponseKDPOSKELURAHAN } from './kelurahanResponseKDPOSKELURAHAN';

export interface KelurahanResponse {
  KD_PROPINSI: string;
  KD_DATI2: string;
  KD_KECAMATAN: string;
  KD_KELURAHAN: string;
  KD_SEKTOR: string;
  NM_KELURAHAN: string;
  NO_KELURAHAN?: KelurahanResponseNOKELURAHAN;
  KD_POS_KELURAHAN?: KelurahanResponseKDPOSKELURAHAN;
}
