/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */

export type OpGetSpopListParams = {
/**
 * Search by NM_WP or NOP
 */
search?: string | null;
/**
 * @minimum 1
 */
page?: number;
/**
 * @minimum 1
 * @maximum 100
 */
per_page?: number;
sort_by?: 'NOP' | 'NM_WP' | 'LUAS_BUMI' | null;
sort_order?: 'asc' | 'desc' | null;
};
