/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { UserListResponse } from './userListResponse';

export interface PaginatedUserListResponse {
  data: UserListResponse[];
  total_count: number;
  page: number;
  limit: number;
  total_pages: number;
}
