/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { RegisterRequestNama } from './registerRequestNama';

export interface RegisterRequest {
  email: string;
  /** @minLength 8 */
  password: string;
  /** @minLength 8 */
  password_confirm: string;
  nama?: RegisterRequestNama;
}
