/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { SpopResponse } from './spopResponse';
import type { PaginationMeta } from './paginationMeta';

export interface SpopPaginatedResponse {
  data: SpopResponse[];
  meta: PaginationMeta;
}
