/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { SpopUpdateRequestJNSTRANSAKSIOP } from './spopUpdateRequestJNSTRANSAKSIOP';
import type { SpopUpdateRequestNOFORMULIRSPOP } from './spopUpdateRequestNOFORMULIRSPOP';
import type { SpopUpdateRequestKDPROPINSIBERSAMA } from './spopUpdateRequestKDPROPINSIBERSAMA';
import type { SpopUpdateRequestKDDATI2BERSAMA } from './spopUpdateRequestKDDATI2BERSAMA';
import type { SpopUpdateRequestKDKECAMATANBERSAMA } from './spopUpdateRequestKDKECAMATANBERSAMA';
import type { SpopUpdateRequestKDKELURAHANBERSAMA } from './spopUpdateRequestKDKELURAHANBERSAMA';
import type { SpopUpdateRequestKDBLOKBERSAMA } from './spopUpdateRequestKDBLOKBERSAMA';
import type { SpopUpdateRequestNOURUTBERSAMA } from './spopUpdateRequestNOURUTBERSAMA';
import type { SpopUpdateRequestKDJNSOPBERSAMA } from './spopUpdateRequestKDJNSOPBERSAMA';
import type { SpopUpdateRequestJALANOP } from './spopUpdateRequestJALANOP';
import type { SpopUpdateRequestRWOP } from './spopUpdateRequestRWOP';
import type { SpopUpdateRequestRTOP } from './spopUpdateRequestRTOP';
import type { SpopUpdateRequestBLOKKAVNOOP } from './spopUpdateRequestBLOKKAVNOOP';
import type { SpopUpdateRequestKELURAHANOP } from './spopUpdateRequestKELURAHANOP';
import type { SpopUpdateRequestSUBJEKPAJAKID } from './spopUpdateRequestSUBJEKPAJAKID';
import type { SpopUpdateRequestKDSTATUSWP } from './spopUpdateRequestKDSTATUSWP';
import type { SpopUpdateRequestTGLPENDATAANOP } from './spopUpdateRequestTGLPENDATAANOP';
import type { SpopUpdateRequestNMPENDATAANOP } from './spopUpdateRequestNMPENDATAANOP';
import type { SpopUpdateRequestNIPPENDATA } from './spopUpdateRequestNIPPENDATA';
import type { SpopUpdateRequestTGLPEMERIKSAANOP } from './spopUpdateRequestTGLPEMERIKSAANOP';
import type { SpopUpdateRequestNMPEMERIKSAANOP } from './spopUpdateRequestNMPEMERIKSAANOP';
import type { SpopUpdateRequestNIPPEMERIKSAOP } from './spopUpdateRequestNIPPEMERIKSAOP';
import type { SpopUpdateRequestLUASBUMI } from './spopUpdateRequestLUASBUMI';
import type { SpopUpdateRequestKDZNT } from './spopUpdateRequestKDZNT';
import type { SpopUpdateRequestJNSBUMI } from './spopUpdateRequestJNSBUMI';
import type { SpopUpdateRequestNILAISISTEMBUMI } from './spopUpdateRequestNILAISISTEMBUMI';
import type { SpopUpdateRequestNOPERSIL } from './spopUpdateRequestNOPERSIL';
import type { SpopUpdateRequestKDPROPINSIASAL } from './spopUpdateRequestKDPROPINSIASAL';
import type { SpopUpdateRequestKDDATI2ASAL } from './spopUpdateRequestKDDATI2ASAL';
import type { SpopUpdateRequestKDKECAMATANASAL } from './spopUpdateRequestKDKECAMATANASAL';
import type { SpopUpdateRequestKDKELURAHANASAL } from './spopUpdateRequestKDKELURAHANASAL';
import type { SpopUpdateRequestKDBLOKASAL } from './spopUpdateRequestKDBLOKASAL';
import type { SpopUpdateRequestNOURUTASAL } from './spopUpdateRequestNOURUTASAL';
import type { SpopUpdateRequestKDJNSOPASAL } from './spopUpdateRequestKDJNSOPASAL';
import type { SpopUpdateRequestNOSPPTLAMA } from './spopUpdateRequestNOSPPTLAMA';

/**
 * Request untuk update SPOP (sama dengan create tapi semua optional kecuali yang diubah)
 */
export interface SpopUpdateRequest {
  JNS_TRANSAKSI_OP?: SpopUpdateRequestJNSTRANSAKSIOP;
  NO_FORMULIR_SPOP?: SpopUpdateRequestNOFORMULIRSPOP;
  KD_PROPINSI_BERSAMA?: SpopUpdateRequestKDPROPINSIBERSAMA;
  KD_DATI2_BERSAMA?: SpopUpdateRequestKDDATI2BERSAMA;
  KD_KECAMATAN_BERSAMA?: SpopUpdateRequestKDKECAMATANBERSAMA;
  KD_KELURAHAN_BERSAMA?: SpopUpdateRequestKDKELURAHANBERSAMA;
  KD_BLOK_BERSAMA?: SpopUpdateRequestKDBLOKBERSAMA;
  NO_URUT_BERSAMA?: SpopUpdateRequestNOURUTBERSAMA;
  KD_JNS_OP_BERSAMA?: SpopUpdateRequestKDJNSOPBERSAMA;
  JALAN_OP?: SpopUpdateRequestJALANOP;
  RW_OP?: SpopUpdateRequestRWOP;
  RT_OP?: SpopUpdateRequestRTOP;
  BLOK_KAV_NO_OP?: SpopUpdateRequestBLOKKAVNOOP;
  KELURAHAN_OP?: SpopUpdateRequestKELURAHANOP;
  SUBJEK_PAJAK_ID?: SpopUpdateRequestSUBJEKPAJAKID;
  KD_STATUS_WP?: SpopUpdateRequestKDSTATUSWP;
  TGL_PENDATAAN_OP?: SpopUpdateRequestTGLPENDATAANOP;
  NM_PENDATAAN_OP?: SpopUpdateRequestNMPENDATAANOP;
  NIP_PENDATA?: SpopUpdateRequestNIPPENDATA;
  TGL_PEMERIKSAAN_OP?: SpopUpdateRequestTGLPEMERIKSAANOP;
  NM_PEMERIKSAAN_OP?: SpopUpdateRequestNMPEMERIKSAANOP;
  NIP_PEMERIKSA_OP?: SpopUpdateRequestNIPPEMERIKSAOP;
  LUAS_BUMI?: SpopUpdateRequestLUASBUMI;
  KD_ZNT?: SpopUpdateRequestKDZNT;
  JNS_BUMI?: SpopUpdateRequestJNSBUMI;
  NILAI_SISTEM_BUMI?: SpopUpdateRequestNILAISISTEMBUMI;
  NO_PERSIL?: SpopUpdateRequestNOPERSIL;
  KD_PROPINSI_ASAL?: SpopUpdateRequestKDPROPINSIASAL;
  KD_DATI2_ASAL?: SpopUpdateRequestKDDATI2ASAL;
  KD_KECAMATAN_ASAL?: SpopUpdateRequestKDKECAMATANASAL;
  KD_KELURAHAN_ASAL?: SpopUpdateRequestKDKELURAHANASAL;
  KD_BLOK_ASAL?: SpopUpdateRequestKDBLOKASAL;
  NO_URUT_ASAL?: SpopUpdateRequestNOURUTASAL;
  KD_JNS_OP_ASAL?: SpopUpdateRequestKDJNSOPASAL;
  NO_SPPT_LAMA?: SpopUpdateRequestNOSPPTLAMA;
}
