/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { SpopResponseNMWP } from './spopResponseNMWP';
import type { SpopResponseKDPROPINSIASAL } from './spopResponseKDPROPINSIASAL';
import type { SpopResponseJALANOP } from './spopResponseJALANOP';
import type { SpopResponseJNSBUMI } from './spopResponseJNSBUMI';
import type { SpopResponseNIPPEMERIKSAOP } from './spopResponseNIPPEMERIKSAOP';
import type { SpopResponseKDPROPINSIBERSAMA } from './spopResponseKDPROPINSIBERSAMA';
import type { SpopResponseKDDATI2ASAL } from './spopResponseKDDATI2ASAL';
import type { SpopResponseBLOKKAVNOOP } from './spopResponseBLOKKAVNOOP';
import type { SpopResponseNOPERSIL } from './spopResponseNOPERSIL';
import type { SpopResponseKDDATI2BERSAMA } from './spopResponseKDDATI2BERSAMA';
import type { SpopResponseKDKECAMATANASAL } from './spopResponseKDKECAMATANASAL';
import type { SpopResponseKELURAHANOP } from './spopResponseKELURAHANOP';
import type { SpopResponseKDKECAMATANBERSAMA } from './spopResponseKDKECAMATANBERSAMA';
import type { SpopResponseKDKELURAHANASAL } from './spopResponseKDKELURAHANASAL';
import type { SpopResponseRWOP } from './spopResponseRWOP';
import type { SpopResponseNMPENDATAANOP } from './spopResponseNMPENDATAANOP';
import type { SpopResponseKDKELURAHANBERSAMA } from './spopResponseKDKELURAHANBERSAMA';
import type { SpopResponseKDBLOKASAL } from './spopResponseKDBLOKASAL';
import type { SpopResponseRTOP } from './spopResponseRTOP';
import type { SpopResponseKDBLOKBERSAMA } from './spopResponseKDBLOKBERSAMA';
import type { SpopResponseNOURUTASAL } from './spopResponseNOURUTASAL';
import type { SpopResponseKDSTATUSWP } from './spopResponseKDSTATUSWP';
import type { SpopResponseNIPPENDATA } from './spopResponseNIPPENDATA';
import type { SpopResponseNOURUTBERSAMA } from './spopResponseNOURUTBERSAMA';
import type { SpopResponseKDJNSOPASAL } from './spopResponseKDJNSOPASAL';
import type { SpopResponseNOFORMULIRSPOP } from './spopResponseNOFORMULIRSPOP';
import type { SpopResponseKDJNSOPBERSAMA } from './spopResponseKDJNSOPBERSAMA';
import type { SpopResponseNOSPPTLAMA } from './spopResponseNOSPPTLAMA';
import type { SpopResponseKDZNT } from './spopResponseKDZNT';
import type { SpopResponseNMPEMERIKSAANOP } from './spopResponseNMPEMERIKSAANOP';

export interface SpopResponse {
  NM_WP?: SpopResponseNMWP;
  JNS_TRANSAKSI_OP: string;
  KD_PROPINSI_ASAL?: SpopResponseKDPROPINSIASAL;
  JALAN_OP?: SpopResponseJALANOP;
  JNS_BUMI?: SpopResponseJNSBUMI;
  NIP_PEMERIKSA_OP?: SpopResponseNIPPEMERIKSAOP;
  KD_PROPINSI_BERSAMA?: SpopResponseKDPROPINSIBERSAMA;
  KD_DATI2_ASAL?: SpopResponseKDDATI2ASAL;
  BLOK_KAV_NO_OP?: SpopResponseBLOKKAVNOOP;
  NILAI_SISTEM_BUMI: number;
  NO_PERSIL: SpopResponseNOPERSIL;
  KD_BLOK: string;
  KD_DATI2_BERSAMA?: SpopResponseKDDATI2BERSAMA;
  KD_KECAMATAN_ASAL?: SpopResponseKDKECAMATANASAL;
  KELURAHAN_OP?: SpopResponseKELURAHANOP;
  TGL_PENDATAAN_OP: string;
  KD_DATI2: string;
  KD_KECAMATAN_BERSAMA?: SpopResponseKDKECAMATANBERSAMA;
  KD_KELURAHAN_ASAL?: SpopResponseKDKELURAHANASAL;
  RW_OP?: SpopResponseRWOP;
  NM_PENDATAAN_OP?: SpopResponseNMPENDATAANOP;
  NO_URUT: string;
  KD_KELURAHAN_BERSAMA?: SpopResponseKDKELURAHANBERSAMA;
  KD_BLOK_ASAL?: SpopResponseKDBLOKASAL;
  RT_OP?: SpopResponseRTOP;
  KD_KELURAHAN: string;
  KD_JNS_OP: string;
  KD_BLOK_BERSAMA?: SpopResponseKDBLOKBERSAMA;
  NO_URUT_ASAL?: SpopResponseNOURUTASAL;
  KD_STATUS_WP?: SpopResponseKDSTATUSWP;
  NIP_PENDATA?: SpopResponseNIPPENDATA;
  KD_PROPINSI: string;
  KD_KECAMATAN: string;
  SUBJEK_PAJAK_ID: string;
  NO_URUT_BERSAMA?: SpopResponseNOURUTBERSAMA;
  KD_JNS_OP_ASAL?: SpopResponseKDJNSOPASAL;
  LUAS_BUMI: number;
  TGL_PEMERIKSAAN_OP: string;
  NO_FORMULIR_SPOP?: SpopResponseNOFORMULIRSPOP;
  KD_JNS_OP_BERSAMA?: SpopResponseKDJNSOPBERSAMA;
  NO_SPPT_LAMA?: SpopResponseNOSPPTLAMA;
  KD_ZNT?: SpopResponseKDZNT;
  NM_PEMERIKSAAN_OP?: SpopResponseNMPEMERIKSAANOP;
}
