/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { SpopListResponse } from './spopListResponse';
import type { PaginationMeta } from './paginationMeta';

/**
 * Response pagination untuk list SPOP
 */
export interface SpopListPaginatedResponse {
  data: SpopListResponse[];
  meta: PaginationMeta;
}
