/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { SpopCreateRequestJNSTRANSAKSIOP } from './spopCreateRequestJNSTRANSAKSIOP';
import type { SpopCreateRequestNOFORMULIRSPOP } from './spopCreateRequestNOFORMULIRSPOP';
import type { SpopCreateRequestKDPROPINSIBERSAMA } from './spopCreateRequestKDPROPINSIBERSAMA';
import type { SpopCreateRequestKDDATI2BERSAMA } from './spopCreateRequestKDDATI2BERSAMA';
import type { SpopCreateRequestKDKECAMATANBERSAMA } from './spopCreateRequestKDKECAMATANBERSAMA';
import type { SpopCreateRequestKDKELURAHANBERSAMA } from './spopCreateRequestKDKELURAHANBERSAMA';
import type { SpopCreateRequestKDBLOKBERSAMA } from './spopCreateRequestKDBLOKBERSAMA';
import type { SpopCreateRequestNOURUTBERSAMA } from './spopCreateRequestNOURUTBERSAMA';
import type { SpopCreateRequestKDJNSOPBERSAMA } from './spopCreateRequestKDJNSOPBERSAMA';
import type { SpopCreateRequestJALANOP } from './spopCreateRequestJALANOP';
import type { SpopCreateRequestRWOP } from './spopCreateRequestRWOP';
import type { SpopCreateRequestRTOP } from './spopCreateRequestRTOP';
import type { SpopCreateRequestBLOKKAVNOOP } from './spopCreateRequestBLOKKAVNOOP';
import type { SpopCreateRequestKELURAHANOP } from './spopCreateRequestKELURAHANOP';
import type { SpopCreateRequestSUBJEKPAJAKID } from './spopCreateRequestSUBJEKPAJAKID';
import type { SpopCreateRequestKDSTATUSWP } from './spopCreateRequestKDSTATUSWP';
import type { SpopCreateRequestTGLPENDATAANOP } from './spopCreateRequestTGLPENDATAANOP';
import type { SpopCreateRequestNMPENDATAANOP } from './spopCreateRequestNMPENDATAANOP';
import type { SpopCreateRequestNIPPENDATA } from './spopCreateRequestNIPPENDATA';
import type { SpopCreateRequestTGLPEMERIKSAANOP } from './spopCreateRequestTGLPEMERIKSAANOP';
import type { SpopCreateRequestNMPEMERIKSAANOP } from './spopCreateRequestNMPEMERIKSAANOP';
import type { SpopCreateRequestNIPPEMERIKSAOP } from './spopCreateRequestNIPPEMERIKSAOP';
import type { SpopCreateRequestLUASBUMI } from './spopCreateRequestLUASBUMI';
import type { SpopCreateRequestKDZNT } from './spopCreateRequestKDZNT';
import type { SpopCreateRequestJNSBUMI } from './spopCreateRequestJNSBUMI';
import type { SpopCreateRequestNILAISISTEMBUMI } from './spopCreateRequestNILAISISTEMBUMI';
import type { SpopCreateRequestNOPERSIL } from './spopCreateRequestNOPERSIL';
import type { SpopCreateRequestKDPROPINSIASAL } from './spopCreateRequestKDPROPINSIASAL';
import type { SpopCreateRequestKDDATI2ASAL } from './spopCreateRequestKDDATI2ASAL';
import type { SpopCreateRequestKDKECAMATANASAL } from './spopCreateRequestKDKECAMATANASAL';
import type { SpopCreateRequestKDKELURAHANASAL } from './spopCreateRequestKDKELURAHANASAL';
import type { SpopCreateRequestKDBLOKASAL } from './spopCreateRequestKDBLOKASAL';
import type { SpopCreateRequestNOURUTASAL } from './spopCreateRequestNOURUTASAL';
import type { SpopCreateRequestKDJNSOPASAL } from './spopCreateRequestKDJNSOPASAL';
import type { SpopCreateRequestNOSPPTLAMA } from './spopCreateRequestNOSPPTLAMA';

/**
 * Request untuk create/update SPOP (form lengkap)
 */
export interface SpopCreateRequest {
  KD_PROPINSI: string;
  KD_DATI2: string;
  KD_KECAMATAN: string;
  KD_KELURAHAN: string;
  KD_BLOK: string;
  NO_URUT: string;
  KD_JNS_OP: string;
  JNS_TRANSAKSI_OP?: SpopCreateRequestJNSTRANSAKSIOP;
  NO_FORMULIR_SPOP?: SpopCreateRequestNOFORMULIRSPOP;
  KD_PROPINSI_BERSAMA?: SpopCreateRequestKDPROPINSIBERSAMA;
  KD_DATI2_BERSAMA?: SpopCreateRequestKDDATI2BERSAMA;
  KD_KECAMATAN_BERSAMA?: SpopCreateRequestKDKECAMATANBERSAMA;
  KD_KELURAHAN_BERSAMA?: SpopCreateRequestKDKELURAHANBERSAMA;
  KD_BLOK_BERSAMA?: SpopCreateRequestKDBLOKBERSAMA;
  NO_URUT_BERSAMA?: SpopCreateRequestNOURUTBERSAMA;
  KD_JNS_OP_BERSAMA?: SpopCreateRequestKDJNSOPBERSAMA;
  JALAN_OP?: SpopCreateRequestJALANOP;
  RW_OP?: SpopCreateRequestRWOP;
  RT_OP?: SpopCreateRequestRTOP;
  BLOK_KAV_NO_OP?: SpopCreateRequestBLOKKAVNOOP;
  KELURAHAN_OP?: SpopCreateRequestKELURAHANOP;
  SUBJEK_PAJAK_ID?: SpopCreateRequestSUBJEKPAJAKID;
  KD_STATUS_WP?: SpopCreateRequestKDSTATUSWP;
  TGL_PENDATAAN_OP?: SpopCreateRequestTGLPENDATAANOP;
  NM_PENDATAAN_OP?: SpopCreateRequestNMPENDATAANOP;
  NIP_PENDATA?: SpopCreateRequestNIPPENDATA;
  TGL_PEMERIKSAAN_OP?: SpopCreateRequestTGLPEMERIKSAANOP;
  NM_PEMERIKSAAN_OP?: SpopCreateRequestNMPEMERIKSAANOP;
  NIP_PEMERIKSA_OP?: SpopCreateRequestNIPPEMERIKSAOP;
  LUAS_BUMI?: SpopCreateRequestLUASBUMI;
  KD_ZNT?: SpopCreateRequestKDZNT;
  JNS_BUMI?: SpopCreateRequestJNSBUMI;
  NILAI_SISTEM_BUMI?: SpopCreateRequestNILAISISTEMBUMI;
  NO_PERSIL?: SpopCreateRequestNOPERSIL;
  KD_PROPINSI_ASAL?: SpopCreateRequestKDPROPINSIASAL;
  KD_DATI2_ASAL?: SpopCreateRequestKDDATI2ASAL;
  KD_KECAMATAN_ASAL?: SpopCreateRequestKDKECAMATANASAL;
  KD_KELURAHAN_ASAL?: SpopCreateRequestKDKELURAHANASAL;
  KD_BLOK_ASAL?: SpopCreateRequestKDBLOKASAL;
  NO_URUT_ASAL?: SpopCreateRequestNOURUTASAL;
  KD_JNS_OP_ASAL?: SpopCreateRequestKDJNSOPASAL;
  NO_SPPT_LAMA?: SpopCreateRequestNOSPPTLAMA;
}
