/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { SpopDetailResponseSUBJEKPAJAKID } from './spopDetailResponseSUBJEKPAJAKID';
import type { SpopDetailResponseNOFORMULIRSPOP } from './spopDetailResponseNOFORMULIRSPOP';
import type { SpopDetailResponseJNSTRANSAKSIOP } from './spopDetailResponseJNSTRANSAKSIOP';
import type { SpopDetailResponseKDPROPINSIBERSAMA } from './spopDetailResponseKDPROPINSIBERSAMA';
import type { SpopDetailResponseKDDATI2BERSAMA } from './spopDetailResponseKDDATI2BERSAMA';
import type { SpopDetailResponseKDKECAMATANBERSAMA } from './spopDetailResponseKDKECAMATANBERSAMA';
import type { SpopDetailResponseKDKELURAHANBERSAMA } from './spopDetailResponseKDKELURAHANBERSAMA';
import type { SpopDetailResponseKDBLOKBERSAMA } from './spopDetailResponseKDBLOKBERSAMA';
import type { SpopDetailResponseNOURUTBERSAMA } from './spopDetailResponseNOURUTBERSAMA';
import type { SpopDetailResponseKDJNSOPBERSAMA } from './spopDetailResponseKDJNSOPBERSAMA';
import type { SpopDetailResponseKDPROPINSIASAL } from './spopDetailResponseKDPROPINSIASAL';
import type { SpopDetailResponseKDDATI2ASAL } from './spopDetailResponseKDDATI2ASAL';
import type { SpopDetailResponseKDKECAMATANASAL } from './spopDetailResponseKDKECAMATANASAL';
import type { SpopDetailResponseKDKELURAHANASAL } from './spopDetailResponseKDKELURAHANASAL';
import type { SpopDetailResponseKDBLOKASAL } from './spopDetailResponseKDBLOKASAL';
import type { SpopDetailResponseNOURUTASAL } from './spopDetailResponseNOURUTASAL';
import type { SpopDetailResponseKDJNSOPASAL } from './spopDetailResponseKDJNSOPASAL';
import type { SpopDetailResponseNOSPPTLAMA } from './spopDetailResponseNOSPPTLAMA';
import type { SpopDetailResponseJALANOP } from './spopDetailResponseJALANOP';
import type { SpopDetailResponseBLOKKAVNOOP } from './spopDetailResponseBLOKKAVNOOP';
import type { SpopDetailResponseKELURAHANOP } from './spopDetailResponseKELURAHANOP';
import type { SpopDetailResponseRWOP } from './spopDetailResponseRWOP';
import type { SpopDetailResponseRTOP } from './spopDetailResponseRTOP';
import type { SpopDetailResponseKDSTATUSWP } from './spopDetailResponseKDSTATUSWP';
import type { SpopDetailResponseLUASBUMI } from './spopDetailResponseLUASBUMI';
import type { SpopDetailResponseKDZNT } from './spopDetailResponseKDZNT';
import type { SpopDetailResponseJNSBUMI } from './spopDetailResponseJNSBUMI';
import type { SpopDetailResponseNILAISISTEMBUMI } from './spopDetailResponseNILAISISTEMBUMI';
import type { SpopDetailResponseTGLPENDATAANOP } from './spopDetailResponseTGLPENDATAANOP';
import type { SpopDetailResponseNMPENDATAANOP } from './spopDetailResponseNMPENDATAANOP';
import type { SpopDetailResponseNIPPENDATA } from './spopDetailResponseNIPPENDATA';
import type { SpopDetailResponseTGLPEMERIKSAANOP } from './spopDetailResponseTGLPEMERIKSAANOP';
import type { SpopDetailResponseNMPEMERIKSAANOP } from './spopDetailResponseNMPEMERIKSAANOP';
import type { SpopDetailResponseNIPPEMERIKSAOP } from './spopDetailResponseNIPPEMERIKSAOP';
import type { SpopDetailResponseNOPERSIL } from './spopDetailResponseNOPERSIL';
import type { SpopDetailResponseNMWP } from './spopDetailResponseNMWP';
import type { SpopDetailResponseJALANWP } from './spopDetailResponseJALANWP';
import type { SpopDetailResponseBLOKKAVNOWP } from './spopDetailResponseBLOKKAVNOWP';
import type { SpopDetailResponseRWWP } from './spopDetailResponseRWWP';
import type { SpopDetailResponseRTWP } from './spopDetailResponseRTWP';
import type { SpopDetailResponseKELURAHANWP } from './spopDetailResponseKELURAHANWP';
import type { SpopDetailResponseKOTAWP } from './spopDetailResponseKOTAWP';
import type { SpopDetailResponseKDPOSWP } from './spopDetailResponseKDPOSWP';
import type { SpopDetailResponseNPWP } from './spopDetailResponseNPWP';

/**
 * Response untuk detail SPOP (untuk edit form)
 */
export interface SpopDetailResponse {
  KD_PROPINSI: string;
  KD_DATI2: string;
  KD_KECAMATAN: string;
  KD_KELURAHAN: string;
  KD_BLOK: string;
  NO_URUT: string;
  KD_JNS_OP: string;
  SUBJEK_PAJAK_ID?: SpopDetailResponseSUBJEKPAJAKID;
  NO_FORMULIR_SPOP?: SpopDetailResponseNOFORMULIRSPOP;
  JNS_TRANSAKSI_OP?: SpopDetailResponseJNSTRANSAKSIOP;
  KD_PROPINSI_BERSAMA?: SpopDetailResponseKDPROPINSIBERSAMA;
  KD_DATI2_BERSAMA?: SpopDetailResponseKDDATI2BERSAMA;
  KD_KECAMATAN_BERSAMA?: SpopDetailResponseKDKECAMATANBERSAMA;
  KD_KELURAHAN_BERSAMA?: SpopDetailResponseKDKELURAHANBERSAMA;
  KD_BLOK_BERSAMA?: SpopDetailResponseKDBLOKBERSAMA;
  NO_URUT_BERSAMA?: SpopDetailResponseNOURUTBERSAMA;
  KD_JNS_OP_BERSAMA?: SpopDetailResponseKDJNSOPBERSAMA;
  KD_PROPINSI_ASAL?: SpopDetailResponseKDPROPINSIASAL;
  KD_DATI2_ASAL?: SpopDetailResponseKDDATI2ASAL;
  KD_KECAMATAN_ASAL?: SpopDetailResponseKDKECAMATANASAL;
  KD_KELURAHAN_ASAL?: SpopDetailResponseKDKELURAHANASAL;
  KD_BLOK_ASAL?: SpopDetailResponseKDBLOKASAL;
  NO_URUT_ASAL?: SpopDetailResponseNOURUTASAL;
  KD_JNS_OP_ASAL?: SpopDetailResponseKDJNSOPASAL;
  NO_SPPT_LAMA?: SpopDetailResponseNOSPPTLAMA;
  JALAN_OP?: SpopDetailResponseJALANOP;
  BLOK_KAV_NO_OP?: SpopDetailResponseBLOKKAVNOOP;
  KELURAHAN_OP?: SpopDetailResponseKELURAHANOP;
  RW_OP?: SpopDetailResponseRWOP;
  RT_OP?: SpopDetailResponseRTOP;
  KD_STATUS_WP?: SpopDetailResponseKDSTATUSWP;
  LUAS_BUMI?: SpopDetailResponseLUASBUMI;
  KD_ZNT?: SpopDetailResponseKDZNT;
  JNS_BUMI?: SpopDetailResponseJNSBUMI;
  NILAI_SISTEM_BUMI?: SpopDetailResponseNILAISISTEMBUMI;
  TGL_PENDATAAN_OP?: SpopDetailResponseTGLPENDATAANOP;
  NM_PENDATAAN_OP?: SpopDetailResponseNMPENDATAANOP;
  NIP_PENDATA?: SpopDetailResponseNIPPENDATA;
  TGL_PEMERIKSAAN_OP?: SpopDetailResponseTGLPEMERIKSAANOP;
  NM_PEMERIKSAAN_OP?: SpopDetailResponseNMPEMERIKSAANOP;
  NIP_PEMERIKSA_OP?: SpopDetailResponseNIPPEMERIKSAOP;
  NO_PERSIL?: SpopDetailResponseNOPERSIL;
  NM_WP?: SpopDetailResponseNMWP;
  JALAN_WP?: SpopDetailResponseJALANWP;
  BLOK_KAV_NO_WP?: SpopDetailResponseBLOKKAVNOWP;
  RW_WP?: SpopDetailResponseRWWP;
  RT_WP?: SpopDetailResponseRTWP;
  KELURAHAN_WP?: SpopDetailResponseKELURAHANWP;
  KOTA_WP?: SpopDetailResponseKOTAWP;
  KD_POS_WP?: SpopDetailResponseKDPOSWP;
  NPWP?: SpopDetailResponseNPWP;
}
