/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { SpopListResponseNMWP } from './spopListResponseNMWP';
import type { SpopListResponseSTATUSPEMBAYARANSPPT } from './spopListResponseSTATUSPEMBAYARANSPPT';
import type { SpopListResponseTHNPAJAKSPPT } from './spopListResponseTHNPAJAKSPPT';
import type { SpopListResponseJALANOP } from './spopListResponseJALANOP';
import type { SpopListResponseKELURAHANOP } from './spopListResponseKELURAHANOP';
import type { SpopListResponseLUASBUMI } from './spopListResponseLUASBUMI';

/**
 * Response untuk list SPOP (tampilan card di admin)
 */
export interface SpopListResponse {
  NOP: string;
  KD_PROPINSI: string;
  KD_DATI2: string;
  KD_KECAMATAN: string;
  KD_KELURAHAN: string;
  KD_BLOK: string;
  NO_URUT: string;
  KD_JNS_OP: string;
  NM_WP?: SpopListResponseNMWP;
  STATUS_PEMBAYARAN_SPPT?: SpopListResponseSTATUSPEMBAYARANSPPT;
  THN_PAJAK_SPPT?: SpopListResponseTHNPAJAKSPPT;
  JALAN_OP?: SpopListResponseJALANOP;
  KELURAHAN_OP?: SpopListResponseKELURAHANOP;
  LUAS_BUMI?: SpopListResponseLUASBUMI;
}
