/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { SpptReportResponseNMKECAMATAN } from './spptReportResponseNMKECAMATAN';
import type { SpptReportResponseNMKELURAHAN } from './spptReportResponseNMKELURAHAN';
import type { SpptReportResponseLEMBARREALISASI } from './spptReportResponseLEMBARREALISASI';
import type { SpptReportResponseLEMBARTUNGGAKAN } from './spptReportResponseLEMBARTUNGGAKAN';
import type { SpptReportResponseLUASBUMISPPT } from './spptReportResponseLUASBUMISPPT';
import type { SpptReportResponseLUASBNGSPPT } from './spptReportResponseLUASBNGSPPT';
import type { SpptReportResponseNJOPBUMISPPT } from './spptReportResponseNJOPBUMISPPT';
import type { SpptReportResponseNJOPBNGSPPT } from './spptReportResponseNJOPBNGSPPT';
import type { SpptReportResponseNJOPSPPT } from './spptReportResponseNJOPSPPT';
import type { SpptReportResponsePBBTERHUTANGSPPT } from './spptReportResponsePBBTERHUTANGSPPT';
import type { SpptReportResponseFAKTORPENGURANGSPPT } from './spptReportResponseFAKTORPENGURANGSPPT';
import type { SpptReportResponsePBBYGHARUSDIBAYARSPPT } from './spptReportResponsePBBYGHARUSDIBAYARSPPT';
import type { SpptReportResponseREALISASI } from './spptReportResponseREALISASI';
import type { SpptReportResponseTUNGGAKAN } from './spptReportResponseTUNGGAKAN';

export interface SpptReportResponse {
  THN_PAJAK_SPPT: string;
  KD_PROPINSI: string;
  KD_DATI2: string;
  KD_KECAMATAN: string;
  KD_KELURAHAN: string;
  NM_KECAMATAN?: SpptReportResponseNMKECAMATAN;
  NM_KELURAHAN?: SpptReportResponseNMKELURAHAN;
  LEMBAR_PBB?: number;
  LEMBAR_REALISASI?: SpptReportResponseLEMBARREALISASI;
  LEMBAR_TUNGGAKAN?: SpptReportResponseLEMBARTUNGGAKAN;
  LUAS_BUMI_SPPT?: SpptReportResponseLUASBUMISPPT;
  LUAS_BNG_SPPT?: SpptReportResponseLUASBNGSPPT;
  NJOP_BUMI_SPPT?: SpptReportResponseNJOPBUMISPPT;
  NJOP_BNG_SPPT?: SpptReportResponseNJOPBNGSPPT;
  NJOP_SPPT?: SpptReportResponseNJOPSPPT;
  PBB_TERHUTANG_SPPT?: SpptReportResponsePBBTERHUTANGSPPT;
  FAKTOR_PENGURANG_SPPT?: SpptReportResponseFAKTORPENGURANGSPPT;
  PBB_YG_HARUS_DIBAYAR_SPPT?: SpptReportResponsePBBYGHARUSDIBAYARSPPT;
  REALISASI?: SpptReportResponseREALISASI;
  TUNGGAKAN?: SpptReportResponseTUNGGAKAN;
}
