/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { SpptReportFiltersResponseKecamatanListItem } from './spptReportFiltersResponseKecamatanListItem';
import type { SpptReportFiltersResponseMaxYear } from './spptReportFiltersResponseMaxYear';

export interface SpptReportFiltersResponse {
  available_years: string[];
  kecamatan_list: SpptReportFiltersResponseKecamatanListItem[];
  max_year?: SpptReportFiltersResponseMaxYear;
}
