/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { SpptResponseNMWPSPPT } from './spptResponseNMWPSPPT';
import type { SpptResponseJLNWPSPPT } from './spptResponseJLNWPSPPT';
import type { SpptResponseBLOKKAVNOWPSPPT } from './spptResponseBLOKKAVNOWPSPPT';
import type { SpptResponseRWWPSPPT } from './spptResponseRWWPSPPT';
import type { SpptResponseRTWPSPPT } from './spptResponseRTWPSPPT';
import type { SpptResponseKELURAHANWPSPPT } from './spptResponseKELURAHANWPSPPT';
import type { SpptResponseKOTAWPSPPT } from './spptResponseKOTAWPSPPT';
import type { SpptResponseKDPOSWPSPPT } from './spptResponseKDPOSWPSPPT';
import type { SpptResponseNPWPSPPT } from './spptResponseNPWPSPPT';
import type { SpptResponseTGLJATUHTEMPOSPPT } from './spptResponseTGLJATUHTEMPOSPPT';
import type { SpptResponseLUASBUMISPPT } from './spptResponseLUASBUMISPPT';
import type { SpptResponseLUASBNGSPPT } from './spptResponseLUASBNGSPPT';
import type { SpptResponseNJOPBUMISPPT } from './spptResponseNJOPBUMISPPT';
import type { SpptResponseNJOPBNGSPPT } from './spptResponseNJOPBNGSPPT';
import type { SpptResponseNJOPSPPT } from './spptResponseNJOPSPPT';
import type { SpptResponseNJOPTKPSPPT } from './spptResponseNJOPTKPSPPT';
import type { SpptResponseNJKPSPPT } from './spptResponseNJKPSPPT';
import type { SpptResponsePBBTERHUTANGSPPT } from './spptResponsePBBTERHUTANGSPPT';
import type { SpptResponsePBBYGHARUSDIBAYARSPPT } from './spptResponsePBBYGHARUSDIBAYARSPPT';
import type { SpptResponseSTATUSPEMBAYARANSPPT } from './spptResponseSTATUSPEMBAYARANSPPT';
import type { SpptResponseSTATUSTAGIHANSPPT } from './spptResponseSTATUSTAGIHANSPPT';
import type { SpptResponseTGLTERBITSPPT } from './spptResponseTGLTERBITSPPT';

export interface SpptResponse {
  KD_PROPINSI: string;
  KD_DATI2: string;
  KD_KECAMATAN: string;
  KD_KELURAHAN: string;
  KD_BLOK: string;
  NO_URUT: string;
  KD_JNS_OP: string;
  THN_PAJAK_SPPT: string;
  NM_WP_SPPT?: SpptResponseNMWPSPPT;
  JLN_WP_SPPT?: SpptResponseJLNWPSPPT;
  BLOK_KAV_NO_WP_SPPT?: SpptResponseBLOKKAVNOWPSPPT;
  RW_WP_SPPT?: SpptResponseRWWPSPPT;
  RT_WP_SPPT?: SpptResponseRTWPSPPT;
  KELURAHAN_WP_SPPT?: SpptResponseKELURAHANWPSPPT;
  KOTA_WP_SPPT?: SpptResponseKOTAWPSPPT;
  KD_POS_WP_SPPT?: SpptResponseKDPOSWPSPPT;
  NPWP_SPPT?: SpptResponseNPWPSPPT;
  TGL_JATUH_TEMPO_SPPT?: SpptResponseTGLJATUHTEMPOSPPT;
  LUAS_BUMI_SPPT?: SpptResponseLUASBUMISPPT;
  LUAS_BNG_SPPT?: SpptResponseLUASBNGSPPT;
  NJOP_BUMI_SPPT?: SpptResponseNJOPBUMISPPT;
  NJOP_BNG_SPPT?: SpptResponseNJOPBNGSPPT;
  NJOP_SPPT?: SpptResponseNJOPSPPT;
  NJOPTKP_SPPT?: SpptResponseNJOPTKPSPPT;
  NJKP_SPPT?: SpptResponseNJKPSPPT;
  PBB_TERHUTANG_SPPT?: SpptResponsePBBTERHUTANGSPPT;
  PBB_YG_HARUS_DIBAYAR_SPPT?: SpptResponsePBBYGHARUSDIBAYARSPPT;
  STATUS_PEMBAYARAN_SPPT?: SpptResponseSTATUSPEMBAYARANSPPT;
  STATUS_TAGIHAN_SPPT?: SpptResponseSTATUSTAGIHANSPPT;
  TGL_TERBIT_SPPT?: SpptResponseTGLTERBITSPPT;
}
