/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { SpptPaymentResponseTotalDenda } from './spptPaymentResponseTotalDenda';
import type { SpptPaymentResponseTotalDibayar } from './spptPaymentResponseTotalDibayar';
import type { SpptPaymentResponseTanggalPembayaran } from './spptPaymentResponseTanggalPembayaran';

export interface SpptPaymentResponse {
  KD_PROPINSI: string;
  KD_DATI2: string;
  KD_KECAMATAN: string;
  KD_KELURAHAN: string;
  KD_BLOK: string;
  NO_URUT: string;
  KD_JNS_OP: string;
  THN_PAJAK_SPPT: string;
  total_denda?: SpptPaymentResponseTotalDenda;
  total_dibayar?: SpptPaymentResponseTotalDibayar;
  tanggal_pembayaran?: SpptPaymentResponseTanggalPembayaran;
}
