/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { SpptReportResponse } from './spptReportResponse';
import type { SpptReportStatsResponse } from './spptReportStatsResponse';

export interface SpptReportTableResponse {
  data: SpptReportResponse[];
  total_count: number;
  stats: SpptReportStatsResponse;
}
