/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { YearlyDataResponse } from './yearlyDataResponse';
import type { SpptReportStatsResponseFilteredByYear } from './spptReportStatsResponseFilteredByYear';
import type { SpptReportStatsResponseFilteredByKecamatan } from './spptReportStatsResponseFilteredByKecamatan';

export interface SpptReportStatsResponse {
  total_kecamatan: number;
  total_kelurahan: number;
  total_luas_bumi: number;
  total_luas_bangunan: number;
  total_njop: number;
  total_pbb_terhutang: number;
  total_pbb_harus_dibayar: number;
  total_realisasi: number;
  total_tunggakan: number;
  total_lembar_ketetapan: number;
  total_lembar_realisasi: number;
  total_lembar_tunggakan: number;
  persentase_realisasi: number;
  persentase_tunggakan: number;
  yearly_data: YearlyDataResponse[];
  filtered_by_year?: SpptReportStatsResponseFilteredByYear;
  filtered_by_kecamatan?: SpptReportStatsResponseFilteredByKecamatan;
}
