/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { SpptYearResponse } from './spptYearResponse';

export interface SpptYearsResponse {
  available_years: SpptYearResponse[];
}
