/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { UserReadNama } from './userReadNama';

export interface UserRead {
  id?: string;
  /** @maxLength 255 */
  email: string;
  nama?: UserReadNama;
  telepon?: string;
  alamat?: string;
  is_active?: boolean;
  is_verified?: boolean;
  is_admin?: boolean;
}
