/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { UserUpdateRequestIsAdmin } from './userUpdateRequestIsAdmin';
import type { UserUpdateRequestIsActive } from './userUpdateRequestIsActive';

export interface UserUpdateRequest {
  is_admin?: UserUpdateRequestIsAdmin;
  is_active?: UserUpdateRequestIsActive;
}
