/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { UserCreateRequestFullName } from './userCreateRequestFullName';

export interface UserCreateRequest {
  email: string;
  full_name?: UserCreateRequestFullName;
  password: string;
  is_admin?: boolean;
  is_active?: boolean;
}
