/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { UserListResponseEmail } from './userListResponseEmail';
import type { UserListResponseFullName } from './userListResponseFullName';
import type { UserListResponseCreatedAt } from './userListResponseCreatedAt';
import type { UserListResponseUpdatedAt } from './userListResponseUpdatedAt';

export interface UserListResponse {
  id: string;
  username: string;
  email?: UserListResponseEmail;
  full_name?: UserListResponseFullName;
  is_admin?: boolean;
  is_active?: boolean;
  created_at?: UserListResponseCreatedAt;
  updated_at?: UserListResponseUpdatedAt;
}
