/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */

export interface YearlyDataResponse {
  year: string;
  pbb_harus_dibayar: number;
  realisasi: number;
  tunggakan: number;
}
