/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import {
  z as zod
} from 'zod';


/**
 * @summary Register
 */
export const authRegisterBodyPasswordMin = 8;
export const authRegisterBodyPasswordConfirmMin = 8;


export const authRegisterBody = zod.object({
  "email": zod.string().email(),
  "password": zod.string().min(authRegisterBodyPasswordMin),
  "password_confirm": zod.string().min(authRegisterBodyPasswordConfirmMin),
  "nama": zod.string().or(zod.null()).optional()
})

export const authRegisterResponseEmailMax = 255;
export const authRegisterResponseNamaMaxOne = 255;
export const authRegisterResponseTeleponDefault = "";export const authRegisterResponseAlamatDefault = "";export const authRegisterResponseIsActiveDefault = false;export const authRegisterResponseIsVerifiedDefault = false;

export const authRegisterResponse = zod.object({
  "id": zod.string().uuid().optional(),
  "email": zod.string().email().max(authRegisterResponseEmailMax),
  "nama": zod.string().max(authRegisterResponseNamaMaxOne).or(zod.null()).optional(),
  "telepon": zod.string().optional(),
  "alamat": zod.string().optional(),
  "is_active": zod.boolean().optional(),
  "is_verified": zod.boolean().optional()
})

/**
 * @summary Login
 */
export const authLoginResponse = zod.object({
  "access_token": zod.string(),
  "refresh_token": zod.string().or(zod.null()).optional()
})

/**
 * @summary Google Redirect
 */
export const authGoogleRedirectResponse = zod.any()

/**
 * @summary Google Callback
 */
export const authGoogleCallbackResponse = zod.any()

/**
 * @summary Me
 */
export const authMeResponseEmailMax = 255;
export const authMeResponseNamaMaxOne = 255;
export const authMeResponseTeleponDefault = "";export const authMeResponseAlamatDefault = "";export const authMeResponseIsActiveDefault = false;export const authMeResponseIsVerifiedDefault = false;

export const authMeResponse = zod.object({
  "id": zod.string().uuid().optional(),
  "email": zod.string().email().max(authMeResponseEmailMax),
  "nama": zod.string().max(authMeResponseNamaMaxOne).or(zod.null()).optional(),
  "telepon": zod.string().optional(),
  "alamat": zod.string().optional(),
  "is_active": zod.boolean().optional(),
  "is_verified": zod.boolean().optional()
})

/**
 * @summary Refresh
 */
export const authRefreshBody = zod.object({
  "refresh_token": zod.string()
})

export const authRefreshResponse = zod.object({
  "access_token": zod.string(),
  "refresh_token": zod.string().or(zod.null()).optional()
})

/**
 * @summary Verification
 */
export const authVerificationQueryParams = zod.object({
  "email": zod.string()
})

export const authVerificationResponse = zod.any()

/**
 * @summary Logout
 */
export const authLogoutResponse = zod.object({
  "message": zod.string()
})

