"""Init

Revision ID: 9877d8245dec
Revises: 
Create Date: 2025-06-24 15:52:04.953385

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '9877d8245dec'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ipbb_user',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('nama', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('telepon', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('alamat', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('password', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ipbb_user_email'), 'ipbb_user', ['email'], unique=True)
    op.drop_table('spop')
    op.drop_table('dat_subjek_pajak')
    op.drop_table('sppt')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sppt',
    sa.Column('KD_PROPINSI', mysql.VARCHAR(length=6), nullable=True),
    sa.Column('KD_DATI2', mysql.VARCHAR(length=6), nullable=True),
    sa.Column('KD_KECAMATAN', mysql.VARCHAR(length=9), nullable=True),
    sa.Column('KD_KELURAHAN', mysql.VARCHAR(length=9), nullable=True),
    sa.Column('KD_BLOK', mysql.VARCHAR(length=9), nullable=True),
    sa.Column('NO_URUT', mysql.VARCHAR(length=12), nullable=True),
    sa.Column('KD_JNS_OP', mysql.VARCHAR(length=3), nullable=True),
    sa.Column('THN_PAJAK_SPPT', mysql.VARCHAR(length=12), nullable=True),
    sa.Column('SIKLUS_SPPT', mysql.TINYINT(), autoincrement=False, nullable=True),
    sa.Column('KD_KANWIL_BANK', mysql.VARCHAR(length=6), nullable=True),
    sa.Column('KD_KPPBB_BANK', mysql.VARCHAR(length=6), nullable=True),
    sa.Column('KD_BANK_TUNGGAL', mysql.VARCHAR(length=6), nullable=True),
    sa.Column('KD_BANK_PERSEPSI', mysql.VARCHAR(length=6), nullable=True),
    sa.Column('KD_TP', mysql.VARCHAR(length=6), nullable=True),
    sa.Column('NM_WP_SPPT', mysql.VARCHAR(length=90), nullable=True),
    sa.Column('JLN_WP_SPPT', mysql.VARCHAR(length=90), nullable=True),
    sa.Column('BLOK_KAV_NO_WP_SPPT', mysql.VARCHAR(length=45), nullable=True),
    sa.Column('RW_WP_SPPT', mysql.VARCHAR(length=6), nullable=True),
    sa.Column('RT_WP_SPPT', mysql.VARCHAR(length=9), nullable=True),
    sa.Column('KELURAHAN_WP_SPPT', mysql.VARCHAR(length=90), nullable=True),
    sa.Column('KOTA_WP_SPPT', mysql.VARCHAR(length=90), nullable=True),
    sa.Column('KD_POS_WP_SPPT', mysql.VARCHAR(length=15), nullable=True),
    sa.Column('NPWP_SPPT', mysql.VARCHAR(length=45), nullable=True),
    sa.Column('NO_PERSIL_SPPT', mysql.VARCHAR(length=15), nullable=True),
    sa.Column('KD_KLS_TANAH', mysql.VARCHAR(length=9), nullable=True),
    sa.Column('THN_AWAL_KLS_TANAH', mysql.YEAR(), nullable=True),
    sa.Column('KD_KLS_BNG', mysql.VARCHAR(length=9), nullable=True),
    sa.Column('THN_AWAL_KLS_BNG', mysql.YEAR(), nullable=True),
    sa.Column('TGL_JATUH_TEMPO_SPPT', sa.DATE(), nullable=True),
    sa.Column('LUAS_BUMI_SPPT', mysql.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('LUAS_BNG_SPPT', mysql.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('NJOP_BUMI_SPPT', mysql.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('NJOP_BNG_SPPT', mysql.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('NJOP_SPPT', mysql.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('NJOPTKP_SPPT', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('NJKP_SPPT', mysql.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('PBB_TERHUTANG_SPPT', mysql.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('FAKTOR_PENGURANG_SPPT', mysql.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('PBB_YG_HARUS_DIBAYAR_SPPT', mysql.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('STATUS_PEMBAYARAN_SPPT', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('STATUS_TAGIHAN_SPPT', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('STATUS_CETAK_SPPT', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('TGL_TERBIT_SPPT', mysql.DATETIME(), nullable=True),
    sa.Column('TGL_CETAK_SPPT', mysql.DATETIME(), nullable=True),
    sa.Column('NIP_PENCETAK_SPPT', mysql.VARCHAR(length=60), nullable=True),
    mysql_default_charset='armscii8',
    mysql_engine='InnoDB'
    )
    op.create_table('dat_subjek_pajak',
    sa.Column('SUBJEK_PAJAK_ID', mysql.VARCHAR(length=90), nullable=True),
    sa.Column('NM_WP', mysql.VARCHAR(length=90), nullable=True),
    sa.Column('JALAN_WP', mysql.VARCHAR(length=90), nullable=True),
    sa.Column('BLOK_KAV_NO_WP', mysql.VARCHAR(length=45), nullable=True),
    sa.Column('RW_WP', mysql.VARCHAR(length=6), nullable=True),
    sa.Column('RT_WP', mysql.VARCHAR(length=9), nullable=True),
    sa.Column('KELURAHAN_WP', mysql.VARCHAR(length=90), nullable=True),
    sa.Column('KOTA_WP', mysql.VARCHAR(length=90), nullable=True),
    sa.Column('KD_POS_WP', mysql.VARCHAR(length=15), nullable=True),
    sa.Column('TELP_WP', mysql.VARCHAR(length=60), nullable=True),
    sa.Column('NPWP', mysql.VARCHAR(length=45), nullable=True),
    sa.Column('STATUS_PEKERJAAN_WP', mysql.VARCHAR(length=3), nullable=True),
    sa.Column('EMAIL_WP', mysql.VARCHAR(length=150), nullable=True),
    mysql_default_charset='armscii8',
    mysql_engine='InnoDB'
    )
    op.create_table('spop',
    sa.Column('KD_PROPINSI', mysql.VARCHAR(length=6), nullable=True),
    sa.Column('KD_DATI2', mysql.VARCHAR(length=6), nullable=True),
    sa.Column('KD_KECAMATAN', mysql.VARCHAR(length=9), nullable=True),
    sa.Column('KD_KELURAHAN', mysql.VARCHAR(length=9), nullable=True),
    sa.Column('KD_BLOK', mysql.VARCHAR(length=9), nullable=True),
    sa.Column('NO_URUT', mysql.VARCHAR(length=12), nullable=True),
    sa.Column('KD_JNS_OP', mysql.VARCHAR(length=3), nullable=True),
    sa.Column('SUBJEK_PAJAK_ID', mysql.VARCHAR(length=90), nullable=True),
    sa.Column('NO_FORMULIR_SPOP', mysql.VARCHAR(length=33), nullable=True),
    sa.Column('JNS_TRANSAKSI_OP', mysql.VARCHAR(length=3), nullable=True),
    sa.Column('KD_PROPINSI_BERSAMA', mysql.VARCHAR(length=6), nullable=True),
    sa.Column('KD_DATI2_BERSAMA', mysql.VARCHAR(length=6), nullable=True),
    sa.Column('KD_KECAMATAN_BERSAMA', mysql.VARCHAR(length=9), nullable=True),
    sa.Column('KD_KELURAHAN_BERSAMA', mysql.VARCHAR(length=9), nullable=True),
    sa.Column('KD_BLOK_BERSAMA', mysql.VARCHAR(length=9), nullable=True),
    sa.Column('NO_URUT_BERSAMA', mysql.VARCHAR(length=12), nullable=True),
    sa.Column('KD_JNS_OP_BERSAMA', mysql.VARCHAR(length=3), nullable=True),
    sa.Column('KD_PROPINSI_ASAL', mysql.VARCHAR(length=6), nullable=True),
    sa.Column('KD_DATI2_ASAL', mysql.VARCHAR(length=6), nullable=True),
    sa.Column('KD_KECAMATAN_ASAL', mysql.VARCHAR(length=9), nullable=True),
    sa.Column('KD_KELURAHAN_ASAL', mysql.VARCHAR(length=9), nullable=True),
    sa.Column('KD_BLOK_ASAL', mysql.VARCHAR(length=9), nullable=True),
    sa.Column('NO_URUT_ASAL', mysql.VARCHAR(length=12), nullable=True),
    sa.Column('KD_JNS_OP_ASAL', mysql.VARCHAR(length=3), nullable=True),
    sa.Column('NO_SPPT_LAMA', mysql.VARCHAR(length=54), nullable=True),
    sa.Column('JALAN_OP', mysql.VARCHAR(length=90), nullable=True),
    sa.Column('BLOK_KAV_NO_OP', mysql.VARCHAR(length=45), nullable=True),
    sa.Column('KELURAHAN_OP', mysql.VARCHAR(length=90), nullable=True),
    sa.Column('RW_OP', mysql.VARCHAR(length=6), nullable=True),
    sa.Column('RT_OP', mysql.VARCHAR(length=9), nullable=True),
    sa.Column('KD_STATUS_WP', mysql.VARCHAR(length=3), nullable=True),
    sa.Column('LUAS_BUMI', mysql.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('KD_ZNT', mysql.VARCHAR(length=6), nullable=True),
    sa.Column('JNS_BUMI', mysql.VARCHAR(length=3), nullable=True),
    sa.Column('NILAI_SISTEM_BUMI', mysql.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('TGL_PENDATAAN_OP', sa.DATE(), nullable=True),
    sa.Column('NM_PENDATAAN_OP', mysql.VARCHAR(length=90), nullable=True),
    sa.Column('NIP_PENDATA', mysql.VARCHAR(length=60), nullable=True),
    sa.Column('TGL_PEMERIKSAAN_OP', sa.DATE(), nullable=True),
    sa.Column('NM_PEMERIKSAAN_OP', mysql.VARCHAR(length=90), nullable=True),
    sa.Column('NIP_PEMERIKSA_OP', mysql.VARCHAR(length=60), nullable=True),
    sa.Column('NO_PERSIL', mysql.VARCHAR(length=15), nullable=True),
    mysql_default_charset='armscii8',
    mysql_engine='InnoDB'
    )
    op.drop_index(op.f('ix_ipbb_user_email'), table_name='ipbb_user')
    op.drop_table('ipbb_user')
    # ### end Alembic commands ###
