"""pbb

Revision ID: e194bab6a939
Revises: 727916fe3189
Create Date: 2025-06-24 16:20:29.944040

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = 'e194bab6a939'
down_revision: Union[str, None] = '727916fe3189'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dat_subjek_pajak',
    sa.Column('SUBJEK_PAJAK_ID', sqlmodel.sql.sqltypes.AutoString(length=90), nullable=False),
    sa.Column('NM_WP', sqlmodel.sql.sqltypes.AutoString(length=90), nullable=True),
    sa.Column('JALAN_WP', sqlmodel.sql.sqltypes.AutoString(length=90), nullable=True),
    sa.Column('BLOK_KAV_NO_WP', sqlmodel.sql.sqltypes.AutoString(length=45), nullable=True),
    sa.Column('RW_WP', sqlmodel.sql.sqltypes.AutoString(length=6), nullable=True),
    sa.Column('RT_WP', sqlmodel.sql.sqltypes.AutoString(length=9), nullable=True),
    sa.Column('KELURAHAN_WP', sqlmodel.sql.sqltypes.AutoString(length=90), nullable=True),
    sa.Column('KOTA_WP', sqlmodel.sql.sqltypes.AutoString(length=90), nullable=True),
    sa.Column('KD_POS_WP', sqlmodel.sql.sqltypes.AutoString(length=15), nullable=True),
    sa.Column('TELP_WP', sqlmodel.sql.sqltypes.AutoString(length=60), nullable=True),
    sa.Column('NPWP', sqlmodel.sql.sqltypes.AutoString(length=45), nullable=True),
    sa.Column('STATUS_PEKERJAAN_WP', sqlmodel.sql.sqltypes.AutoString(length=3), nullable=True),
    sa.Column('EMAIL_WP', sqlmodel.sql.sqltypes.AutoString(length=150), nullable=True),
    sa.PrimaryKeyConstraint('SUBJEK_PAJAK_ID')
    )
    op.create_table('spop',
    sa.Column('KD_PROPINSI', sqlmodel.sql.sqltypes.AutoString(length=6), nullable=False),
    sa.Column('KD_DATI2', sqlmodel.sql.sqltypes.AutoString(length=6), nullable=False),
    sa.Column('KD_KECAMATAN', sqlmodel.sql.sqltypes.AutoString(length=9), nullable=False),
    sa.Column('KD_KELURAHAN', sqlmodel.sql.sqltypes.AutoString(length=9), nullable=False),
    sa.Column('KD_BLOK', sqlmodel.sql.sqltypes.AutoString(length=9), nullable=False),
    sa.Column('NO_URUT', sqlmodel.sql.sqltypes.AutoString(length=12), nullable=False),
    sa.Column('KD_JNS_OP', sqlmodel.sql.sqltypes.AutoString(length=3), nullable=False),
    sa.Column('SUBJEK_PAJAK_ID', sqlmodel.sql.sqltypes.AutoString(length=90), nullable=True),
    sa.Column('NO_FORMULIR_SPOP', sqlmodel.sql.sqltypes.AutoString(length=33), nullable=True),
    sa.Column('JNS_TRANSAKSI_OP', sqlmodel.sql.sqltypes.AutoString(length=3), nullable=True),
    sa.Column('KD_PROPINSI_BERSAMA', sqlmodel.sql.sqltypes.AutoString(length=6), nullable=True),
    sa.Column('KD_DATI2_BERSAMA', sqlmodel.sql.sqltypes.AutoString(length=6), nullable=True),
    sa.Column('KD_KECAMATAN_BERSAMA', sqlmodel.sql.sqltypes.AutoString(length=9), nullable=True),
    sa.Column('KD_KELURAHAN_BERSAMA', sqlmodel.sql.sqltypes.AutoString(length=9), nullable=True),
    sa.Column('KD_BLOK_BERSAMA', sqlmodel.sql.sqltypes.AutoString(length=9), nullable=True),
    sa.Column('NO_URUT_BERSAMA', sqlmodel.sql.sqltypes.AutoString(length=12), nullable=True),
    sa.Column('KD_JNS_OP_BERSAMA', sqlmodel.sql.sqltypes.AutoString(length=3), nullable=True),
    sa.Column('KD_PROPINSI_ASAL', sqlmodel.sql.sqltypes.AutoString(length=6), nullable=True),
    sa.Column('KD_DATI2_ASAL', sqlmodel.sql.sqltypes.AutoString(length=6), nullable=True),
    sa.Column('KD_KECAMATAN_ASAL', sqlmodel.sql.sqltypes.AutoString(length=9), nullable=True),
    sa.Column('KD_KELURAHAN_ASAL', sqlmodel.sql.sqltypes.AutoString(length=9), nullable=True),
    sa.Column('KD_BLOK_ASAL', sqlmodel.sql.sqltypes.AutoString(length=9), nullable=True),
    sa.Column('NO_URUT_ASAL', sqlmodel.sql.sqltypes.AutoString(length=12), nullable=True),
    sa.Column('KD_JNS_OP_ASAL', sqlmodel.sql.sqltypes.AutoString(length=3), nullable=True),
    sa.Column('NO_SPPT_LAMA', sqlmodel.sql.sqltypes.AutoString(length=54), nullable=True),
    sa.Column('JALAN_OP', sqlmodel.sql.sqltypes.AutoString(length=90), nullable=True),
    sa.Column('BLOK_KAV_NO_OP', sqlmodel.sql.sqltypes.AutoString(length=45), nullable=True),
    sa.Column('KELURAHAN_OP', sqlmodel.sql.sqltypes.AutoString(length=90), nullable=True),
    sa.Column('RW_OP', sqlmodel.sql.sqltypes.AutoString(length=6), nullable=True),
    sa.Column('RT_OP', sqlmodel.sql.sqltypes.AutoString(length=9), nullable=True),
    sa.Column('KD_STATUS_WP', sqlmodel.sql.sqltypes.AutoString(length=3), nullable=True),
    sa.Column('LUAS_BUMI', sa.Integer(), nullable=True),
    sa.Column('KD_ZNT', sqlmodel.sql.sqltypes.AutoString(length=6), nullable=True),
    sa.Column('JNS_BUMI', sqlmodel.sql.sqltypes.AutoString(length=3), nullable=True),
    sa.Column('NILAI_SISTEM_BUMI', sa.Integer(), nullable=True),
    sa.Column('TGL_PENDATAAN_OP', sa.Date(), nullable=True),
    sa.Column('NM_PENDATAAN_OP', sqlmodel.sql.sqltypes.AutoString(length=90), nullable=True),
    sa.Column('NIP_PENDATA', sqlmodel.sql.sqltypes.AutoString(length=60), nullable=True),
    sa.Column('TGL_PEMERIKSAAN_OP', sa.Date(), nullable=True),
    sa.Column('NM_PEMERIKSAAN_OP', sqlmodel.sql.sqltypes.AutoString(length=90), nullable=True),
    sa.Column('NIP_PEMERIKSA_OP', sqlmodel.sql.sqltypes.AutoString(length=60), nullable=True),
    sa.Column('NO_PERSIL', sqlmodel.sql.sqltypes.AutoString(length=15), nullable=True),
    sa.PrimaryKeyConstraint('KD_PROPINSI', 'KD_DATI2', 'KD_KECAMATAN', 'KD_KELURAHAN', 'KD_BLOK', 'NO_URUT', 'KD_JNS_OP')
    )
    op.create_table('sppt',
    sa.Column('KD_PROPINSI', sqlmodel.sql.sqltypes.AutoString(length=6), nullable=False),
    sa.Column('KD_DATI2', sqlmodel.sql.sqltypes.AutoString(length=6), nullable=False),
    sa.Column('KD_KECAMATAN', sqlmodel.sql.sqltypes.AutoString(length=9), nullable=False),
    sa.Column('KD_KELURAHAN', sqlmodel.sql.sqltypes.AutoString(length=9), nullable=False),
    sa.Column('KD_BLOK', sqlmodel.sql.sqltypes.AutoString(length=9), nullable=False),
    sa.Column('NO_URUT', sqlmodel.sql.sqltypes.AutoString(length=12), nullable=False),
    sa.Column('KD_JNS_OP', sqlmodel.sql.sqltypes.AutoString(length=3), nullable=False),
    sa.Column('THN_PAJAK_SPPT', sqlmodel.sql.sqltypes.AutoString(length=12), nullable=False),
    sa.Column('SIKLUS_SPPT', sa.Integer(), nullable=True),
    sa.Column('KD_KANWIL_BANK', sqlmodel.sql.sqltypes.AutoString(length=6), nullable=True),
    sa.Column('KD_KPPBB_BANK', sqlmodel.sql.sqltypes.AutoString(length=6), nullable=True),
    sa.Column('KD_BANK_TUNGGAL', sqlmodel.sql.sqltypes.AutoString(length=6), nullable=True),
    sa.Column('KD_BANK_PERSEPSI', sqlmodel.sql.sqltypes.AutoString(length=6), nullable=True),
    sa.Column('KD_TP', sqlmodel.sql.sqltypes.AutoString(length=6), nullable=True),
    sa.Column('NM_WP_SPPT', sqlmodel.sql.sqltypes.AutoString(length=90), nullable=True),
    sa.Column('JLN_WP_SPPT', sqlmodel.sql.sqltypes.AutoString(length=90), nullable=True),
    sa.Column('BLOK_KAV_NO_WP_SPPT', sqlmodel.sql.sqltypes.AutoString(length=45), nullable=True),
    sa.Column('RW_WP_SPPT', sqlmodel.sql.sqltypes.AutoString(length=6), nullable=True),
    sa.Column('RT_WP_SPPT', sqlmodel.sql.sqltypes.AutoString(length=9), nullable=True),
    sa.Column('KELURAHAN_WP_SPPT', sqlmodel.sql.sqltypes.AutoString(length=90), nullable=True),
    sa.Column('KOTA_WP_SPPT', sqlmodel.sql.sqltypes.AutoString(length=90), nullable=True),
    sa.Column('KD_POS_WP_SPPT', sqlmodel.sql.sqltypes.AutoString(length=15), nullable=True),
    sa.Column('NPWP_SPPT', sqlmodel.sql.sqltypes.AutoString(length=45), nullable=True),
    sa.Column('NO_PERSIL_SPPT', sqlmodel.sql.sqltypes.AutoString(length=15), nullable=True),
    sa.Column('KD_KLS_TANAH', sqlmodel.sql.sqltypes.AutoString(length=9), nullable=True),
    sa.Column('THN_AWAL_KLS_TANAH', sa.Integer(), nullable=True),
    sa.Column('KD_KLS_BNG', sqlmodel.sql.sqltypes.AutoString(length=9), nullable=True),
    sa.Column('THN_AWAL_KLS_BNG', sa.Integer(), nullable=True),
    sa.Column('TGL_JATUH_TEMPO_SPPT', sa.Date(), nullable=True),
    sa.Column('LUAS_BUMI_SPPT', sa.Integer(), nullable=True),
    sa.Column('LUAS_BNG_SPPT', sa.Integer(), nullable=True),
    sa.Column('NJOP_BUMI_SPPT', sa.Integer(), nullable=True),
    sa.Column('NJOP_BNG_SPPT', sa.Integer(), nullable=True),
    sa.Column('NJOP_SPPT', sa.Integer(), nullable=True),
    sa.Column('NJOPTKP_SPPT', sa.Integer(), nullable=True),
    sa.Column('NJKP_SPPT', sa.Integer(), nullable=True),
    sa.Column('PBB_TERHUTANG_SPPT', sa.Integer(), nullable=True),
    sa.Column('FAKTOR_PENGURANG_SPPT', sa.Integer(), nullable=True),
    sa.Column('PBB_YG_HARUS_DIBAYAR_SPPT', sa.Integer(), nullable=True),
    sa.Column('STATUS_PEMBAYARAN_SPPT', sa.Boolean(), nullable=True),
    sa.Column('STATUS_TAGIHAN_SPPT', sa.Boolean(), nullable=True),
    sa.Column('STATUS_CETAK_SPPT', sa.Boolean(), nullable=True),
    sa.Column('TGL_TERBIT_SPPT', sa.DateTime(), nullable=True),
    sa.Column('TGL_CETAK_SPPT', sa.DateTime(), nullable=True),
    sa.Column('NIP_PENCETAK_SPPT', sqlmodel.sql.sqltypes.AutoString(length=60), nullable=True),
    sa.PrimaryKeyConstraint('KD_PROPINSI', 'KD_DATI2', 'KD_KECAMATAN', 'KD_KELURAHAN', 'KD_BLOK', 'NO_URUT', 'KD_JNS_OP', 'THN_PAJAK_SPPT')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sppt')
    op.drop_table('spop')
    op.drop_table('dat_subjek_pajak')
    # ### end Alembic commands ###
