"""add is_admin to ipbb_user

Revision ID: f5817754fc0b
Revises: e194bab6a939
Create Date: 2025-09-12 23:47:37.844715

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'f5817754fc0b'
down_revision: Union[str, None] = 'e194bab6a939'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dat_op_bangunan')
    op.alter_column('dat_subjek_pajak', 'SUBJEK_PAJAK_ID',
               existing_type=mysql.VARCHAR(charset='utf8mb3', collation='utf8mb3_general_ci', length=30),
               type_=sqlmodel.sql.sqltypes.AutoString(length=90),
               existing_nullable=False)
    op.alter_column('dat_subjek_pajak', 'NM_WP',
               existing_type=mysql.VARCHAR(charset='utf8mb3', collation='utf8mb3_general_ci', length=30),
               type_=sqlmodel.sql.sqltypes.AutoString(length=90),
               nullable=True)
    op.alter_column('dat_subjek_pajak', 'JALAN_WP',
               existing_type=mysql.VARCHAR(charset='utf8mb3', collation='utf8mb3_general_ci', length=30),
               type_=sqlmodel.sql.sqltypes.AutoString(length=90),
               nullable=True)
    op.alter_column('dat_subjek_pajak', 'BLOK_KAV_NO_WP',
               existing_type=mysql.VARCHAR(charset='utf8mb3', collation='utf8mb3_general_ci', length=15),
               type_=sqlmodel.sql.sqltypes.AutoString(length=45),
               existing_nullable=True)
    op.alter_column('dat_subjek_pajak', 'RW_WP',
               existing_type=mysql.VARCHAR(charset='utf8mb3', collation='utf8mb3_general_ci', length=2),
               type_=sqlmodel.sql.sqltypes.AutoString(length=6),
               existing_nullable=True)
    op.alter_column('dat_subjek_pajak', 'RT_WP',
               existing_type=mysql.VARCHAR(charset='utf8mb3', collation='utf8mb3_general_ci', length=3),
               type_=sqlmodel.sql.sqltypes.AutoString(length=9),
               existing_nullable=True)
    op.alter_column('dat_subjek_pajak', 'KELURAHAN_WP',
               existing_type=mysql.VARCHAR(charset='utf8mb3', collation='utf8mb3_general_ci', length=30),
               type_=sqlmodel.sql.sqltypes.AutoString(length=90),
               existing_nullable=True)
    op.alter_column('dat_subjek_pajak', 'KOTA_WP',
               existing_type=mysql.VARCHAR(charset='utf8mb3', collation='utf8mb3_general_ci', length=30),
               type_=sqlmodel.sql.sqltypes.AutoString(length=90),
               existing_nullable=True)
    op.alter_column('dat_subjek_pajak', 'KD_POS_WP',
               existing_type=mysql.VARCHAR(charset='utf8mb3', collation='utf8mb3_general_ci', length=5),
               type_=sqlmodel.sql.sqltypes.AutoString(length=15),
               existing_nullable=True)
    op.alter_column('dat_subjek_pajak', 'TELP_WP',
               existing_type=mysql.VARCHAR(charset='utf8mb3', collation='utf8mb3_general_ci', length=20),
               type_=sqlmodel.sql.sqltypes.AutoString(length=60),
               existing_nullable=True)
    op.alter_column('dat_subjek_pajak', 'NPWP',
               existing_type=mysql.VARCHAR(charset='utf8mb3', collation='utf8mb3_general_ci', length=15),
               type_=sqlmodel.sql.sqltypes.AutoString(length=45),
               existing_nullable=True)
    op.alter_column('dat_subjek_pajak', 'STATUS_PEKERJAAN_WP',
               existing_type=mysql.VARCHAR(charset='utf8mb3', collation='utf8mb3_general_ci', length=1),
               type_=sqlmodel.sql.sqltypes.AutoString(length=3),
               nullable=True)
    op.alter_column('dat_subjek_pajak', 'EMAIL_WP',
               existing_type=mysql.VARCHAR(length=50),
               type_=sqlmodel.sql.sqltypes.AutoString(length=150),
               existing_nullable=True)
    op.add_column('ipbb_user', sa.Column('is_admin', sa.Boolean(), nullable=False))
    op.alter_column('spop', 'KD_PROPINSI',
               existing_type=mysql.VARCHAR(charset='utf8mb3', collation='utf8mb3_general_ci', length=2),
               type_=sqlmodel.sql.sqltypes.AutoString(length=6),
               existing_nullable=False)
    op.alter_column('spop', 'KD_DATI2',
               existing_type=mysql.VARCHAR(charset='utf8mb3', collation='utf8mb3_general_ci', length=2),
               type_=sqlmodel.sql.sqltypes.AutoString(length=6),
               existing_nullable=False)
    op.alter_column('spop', 'KD_KECAMATAN',
               existing_type=mysql.VARCHAR(charset='utf8mb3', collation='utf8mb3_general_ci', length=3),
               type_=sqlmodel.sql.sqltypes.AutoString(length=9),
               existing_nullable=False)
    op.alter_column('spop', 'KD_KELURAHAN',
               existing_type=mysql.VARCHAR(charset='utf8mb3', collation='utf8mb3_general_ci', length=3),
               type_=sqlmodel.sql.sqltypes.AutoString(length=9),
               existing_nullable=False)
    op.alter_column('spop', 'KD_BLOK',
               existing_type=mysql.VARCHAR(charset='utf8mb3', collation='utf8mb3_general_ci', length=3),
               type_=sqlmodel.sql.sqltypes.AutoString(length=9),
               existing_nullable=False)
    op.alter_column('spop', 'NO_URUT',
               existing_type=mysql.VARCHAR(charset='utf8mb3', collation='utf8mb3_general_ci', length=4),
               type_=sqlmodel.sql.sqltypes.AutoString(length=12),
               existing_nullable=False)
    op.alter_column('spop', 'KD_JNS_OP',
               existing_type=mysql.VARCHAR(charset='utf8mb3', collation='utf8mb3_general_ci', length=1),
               type_=sqlmodel.sql.sqltypes.AutoString(length=3),
               existing_nullable=False)
    op.alter_column('spop', 'SUBJEK_PAJAK_ID',
               existing_type=mysql.VARCHAR(charset='utf8mb3', collation='utf8mb3_general_ci', length=30),
               type_=sqlmodel.sql.sqltypes.AutoString(length=90),
               nullable=True)
    op.alter_column('spop', 'NO_FORMULIR_SPOP',
               existing_type=mysql.VARCHAR(charset='utf8mb3', collation='utf8mb3_general_ci', length=11),
               type_=sqlmodel.sql.sqltypes.AutoString(length=33),
               existing_nullable=True)
    op.alter_column('spop', 'JNS_TRANSAKSI_OP',
               existing_type=mysql.VARCHAR(charset='utf8mb3', collation='utf8mb3_general_ci', length=1),
               type_=sqlmodel.sql.sqltypes.AutoString(length=3),
               nullable=True)
    op.alter_column('spop', 'KD_PROPINSI_BERSAMA',
               existing_type=mysql.VARCHAR(charset='utf8mb3', collation='utf8mb3_general_ci', length=2),
               type_=sqlmodel.sql.sqltypes.AutoString(length=6),
               existing_nullable=True)
    op.alter_column('spop', 'KD_DATI2_BERSAMA',
               existing_type=mysql.VARCHAR(charset='utf8mb3', collation='utf8mb3_general_ci', length=2),
               type_=sqlmodel.sql.sqltypes.AutoString(length=6),
               existing_nullable=True)
    op.alter_column('spop', 'KD_KECAMATAN_BERSAMA',
               existing_type=mysql.VARCHAR(charset='utf8mb3', collation='utf8mb3_general_ci', length=3),
               type_=sqlmodel.sql.sqltypes.AutoString(length=9),
               existing_nullable=True)
    op.alter_column('spop', 'KD_KELURAHAN_BERSAMA',
               existing_type=mysql.VARCHAR(charset='utf8mb3', collation='utf8mb3_general_ci', length=3),
               type_=sqlmodel.sql.sqltypes.AutoString(length=9),
               existing_nullable=True)
    op.alter_column('spop', 'KD_BLOK_BERSAMA',
               existing_type=mysql.VARCHAR(charset='utf8mb3', collation='utf8mb3_general_ci', length=3),
               type_=sqlmodel.sql.sqltypes.AutoString(length=9),
               existing_nullable=True)
    op.alter_column('spop', 'NO_URUT_BERSAMA',
               existing_type=mysql.VARCHAR(charset='utf8mb3', collation='utf8mb3_general_ci', length=4),
               type_=sqlmodel.sql.sqltypes.AutoString(length=12),
               existing_nullable=True)
    op.alter_column('spop', 'KD_JNS_OP_BERSAMA',
               existing_type=mysql.VARCHAR(charset='utf8mb3', collation='utf8mb3_general_ci', length=1),
               type_=sqlmodel.sql.sqltypes.AutoString(length=3),
               existing_nullable=True)
    op.alter_column('spop', 'KD_PROPINSI_ASAL',
               existing_type=mysql.VARCHAR(charset='utf8mb3', collation='utf8mb3_general_ci', length=2),
               type_=sqlmodel.sql.sqltypes.AutoString(length=6),
               existing_nullable=True)
    op.alter_column('spop', 'KD_DATI2_ASAL',
               existing_type=mysql.VARCHAR(charset='utf8mb3', collation='utf8mb3_general_ci', length=2),
               type_=sqlmodel.sql.sqltypes.AutoString(length=6),
               existing_nullable=True)
    op.alter_column('spop', 'KD_KECAMATAN_ASAL',
               existing_type=mysql.VARCHAR(charset='utf8mb3', collation='utf8mb3_general_ci', length=3),
               type_=sqlmodel.sql.sqltypes.AutoString(length=9),
               existing_nullable=True)
    op.alter_column('spop', 'KD_KELURAHAN_ASAL',
               existing_type=mysql.VARCHAR(charset='utf8mb3', collation='utf8mb3_general_ci', length=3),
               type_=sqlmodel.sql.sqltypes.AutoString(length=9),
               existing_nullable=True)
    op.alter_column('spop', 'KD_BLOK_ASAL',
               existing_type=mysql.VARCHAR(charset='utf8mb3', collation='utf8mb3_general_ci', length=3),
               type_=sqlmodel.sql.sqltypes.AutoString(length=9),
               existing_nullable=True)
    op.alter_column('spop', 'NO_URUT_ASAL',
               existing_type=mysql.VARCHAR(charset='utf8mb3', collation='utf8mb3_general_ci', length=4),
               type_=sqlmodel.sql.sqltypes.AutoString(length=12),
               existing_nullable=True)
    op.alter_column('spop', 'KD_JNS_OP_ASAL',
               existing_type=mysql.VARCHAR(charset='utf8mb3', collation='utf8mb3_general_ci', length=1),
               type_=sqlmodel.sql.sqltypes.AutoString(length=3),
               existing_nullable=True)
    op.alter_column('spop', 'NO_SPPT_LAMA',
               existing_type=mysql.VARCHAR(charset='utf8mb3', collation='utf8mb3_general_ci', length=18),
               type_=sqlmodel.sql.sqltypes.AutoString(length=54),
               existing_nullable=True)
    op.alter_column('spop', 'JALAN_OP',
               existing_type=mysql.VARCHAR(charset='utf8mb3', collation='utf8mb3_general_ci', length=30),
               type_=sqlmodel.sql.sqltypes.AutoString(length=90),
               nullable=True)
    op.alter_column('spop', 'BLOK_KAV_NO_OP',
               existing_type=mysql.VARCHAR(charset='utf8mb3', collation='utf8mb3_general_ci', length=15),
               type_=sqlmodel.sql.sqltypes.AutoString(length=45),
               existing_nullable=True)
    op.alter_column('spop', 'KELURAHAN_OP',
               existing_type=mysql.VARCHAR(charset='utf8mb3', collation='utf8mb3_general_ci', length=30),
               type_=sqlmodel.sql.sqltypes.AutoString(length=90),
               existing_nullable=True)
    op.alter_column('spop', 'RW_OP',
               existing_type=mysql.VARCHAR(charset='utf8mb3', collation='utf8mb3_general_ci', length=2),
               type_=sqlmodel.sql.sqltypes.AutoString(length=6),
               existing_nullable=True)
    op.alter_column('spop', 'RT_OP',
               existing_type=mysql.VARCHAR(charset='utf8mb3', collation='utf8mb3_general_ci', length=3),
               type_=sqlmodel.sql.sqltypes.AutoString(length=9),
               existing_nullable=True)
    op.alter_column('spop', 'KD_STATUS_WP',
               existing_type=mysql.VARCHAR(charset='utf8mb3', collation='utf8mb3_general_ci', length=1),
               type_=sqlmodel.sql.sqltypes.AutoString(length=3),
               nullable=True)
    op.alter_column('spop', 'LUAS_BUMI',
               existing_type=mysql.BIGINT(),
               type_=sa.Integer(),
               nullable=True)
    op.alter_column('spop', 'KD_ZNT',
               existing_type=mysql.VARCHAR(charset='utf8mb3', collation='utf8mb3_general_ci', length=2),
               type_=sqlmodel.sql.sqltypes.AutoString(length=6),
               existing_nullable=True)
    op.alter_column('spop', 'JNS_BUMI',
               existing_type=mysql.VARCHAR(charset='utf8mb3', collation='utf8mb3_general_ci', length=1),
               type_=sqlmodel.sql.sqltypes.AutoString(length=3),
               nullable=True)
    op.alter_column('spop', 'NILAI_SISTEM_BUMI',
               existing_type=mysql.BIGINT(),
               type_=sa.Integer(),
               nullable=True,
               existing_server_default=sa.text("'0'"))
    op.alter_column('spop', 'TGL_PENDATAAN_OP',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('spop', 'NM_PENDATAAN_OP',
               existing_type=mysql.VARCHAR(length=30),
               type_=sqlmodel.sql.sqltypes.AutoString(length=90),
               existing_nullable=True)
    op.alter_column('spop', 'NIP_PENDATA',
               existing_type=mysql.VARCHAR(length=20),
               type_=sqlmodel.sql.sqltypes.AutoString(length=60),
               existing_nullable=True)
    op.alter_column('spop', 'TGL_PEMERIKSAAN_OP',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('spop', 'NM_PEMERIKSAAN_OP',
               existing_type=mysql.VARCHAR(length=30),
               type_=sqlmodel.sql.sqltypes.AutoString(length=90),
               existing_nullable=True)
    op.alter_column('spop', 'NIP_PEMERIKSA_OP',
               existing_type=mysql.VARCHAR(length=20),
               type_=sqlmodel.sql.sqltypes.AutoString(length=60),
               existing_nullable=True)
    op.alter_column('spop', 'NO_PERSIL',
               existing_type=mysql.VARCHAR(length=5),
               type_=sqlmodel.sql.sqltypes.AutoString(length=15),
               existing_nullable=True)
    op.alter_column('sppt', 'KD_PROPINSI',
               existing_type=mysql.VARCHAR(charset='utf8mb3', collation='utf8mb3_general_ci', length=2),
               type_=sqlmodel.sql.sqltypes.AutoString(length=6),
               existing_nullable=False)
    op.alter_column('sppt', 'KD_DATI2',
               existing_type=mysql.VARCHAR(charset='utf8mb3', collation='utf8mb3_general_ci', length=2),
               type_=sqlmodel.sql.sqltypes.AutoString(length=6),
               existing_nullable=False)
    op.alter_column('sppt', 'KD_KECAMATAN',
               existing_type=mysql.VARCHAR(charset='utf8mb3', collation='utf8mb3_general_ci', length=3),
               type_=sqlmodel.sql.sqltypes.AutoString(length=9),
               existing_nullable=False)
    op.alter_column('sppt', 'KD_KELURAHAN',
               existing_type=mysql.VARCHAR(charset='utf8mb3', collation='utf8mb3_general_ci', length=3),
               type_=sqlmodel.sql.sqltypes.AutoString(length=9),
               existing_nullable=False)
    op.alter_column('sppt', 'KD_BLOK',
               existing_type=mysql.VARCHAR(charset='utf8mb3', collation='utf8mb3_general_ci', length=3),
               type_=sqlmodel.sql.sqltypes.AutoString(length=9),
               existing_nullable=False)
    op.alter_column('sppt', 'NO_URUT',
               existing_type=mysql.VARCHAR(charset='utf8mb3', collation='utf8mb3_general_ci', length=4),
               type_=sqlmodel.sql.sqltypes.AutoString(length=12),
               existing_nullable=False)
    op.alter_column('sppt', 'KD_JNS_OP',
               existing_type=mysql.VARCHAR(charset='utf8mb3', collation='utf8mb3_general_ci', length=1),
               type_=sqlmodel.sql.sqltypes.AutoString(length=3),
               existing_nullable=False)
    op.alter_column('sppt', 'THN_PAJAK_SPPT',
               existing_type=mysql.VARCHAR(length=4),
               type_=sqlmodel.sql.sqltypes.AutoString(length=12),
               existing_nullable=False)
    op.alter_column('sppt', 'SIKLUS_SPPT',
               existing_type=mysql.TINYINT(),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('sppt', 'KD_KANWIL_BANK',
               existing_type=mysql.VARCHAR(charset='utf8mb3', collation='utf8mb3_general_ci', length=2),
               type_=sqlmodel.sql.sqltypes.AutoString(length=6),
               existing_nullable=True)
    op.alter_column('sppt', 'KD_KPPBB_BANK',
               existing_type=mysql.VARCHAR(charset='utf8mb3', collation='utf8mb3_general_ci', length=2),
               type_=sqlmodel.sql.sqltypes.AutoString(length=6),
               existing_nullable=True)
    op.alter_column('sppt', 'KD_BANK_TUNGGAL',
               existing_type=mysql.VARCHAR(charset='utf8mb3', collation='utf8mb3_general_ci', length=2),
               type_=sqlmodel.sql.sqltypes.AutoString(length=6),
               existing_nullable=True)
    op.alter_column('sppt', 'KD_BANK_PERSEPSI',
               existing_type=mysql.VARCHAR(charset='utf8mb3', collation='utf8mb3_general_ci', length=2),
               type_=sqlmodel.sql.sqltypes.AutoString(length=6),
               existing_nullable=True)
    op.alter_column('sppt', 'KD_TP',
               existing_type=mysql.VARCHAR(charset='utf8mb3', collation='utf8mb3_general_ci', length=2),
               type_=sqlmodel.sql.sqltypes.AutoString(length=6),
               existing_nullable=True)
    op.alter_column('sppt', 'NM_WP_SPPT',
               existing_type=mysql.VARCHAR(charset='utf8mb3', collation='utf8mb3_general_ci', length=30),
               type_=sqlmodel.sql.sqltypes.AutoString(length=90),
               existing_nullable=True)
    op.alter_column('sppt', 'JLN_WP_SPPT',
               existing_type=mysql.VARCHAR(charset='utf8mb3', collation='utf8mb3_general_ci', length=30),
               type_=sqlmodel.sql.sqltypes.AutoString(length=90),
               existing_nullable=True)
    op.alter_column('sppt', 'BLOK_KAV_NO_WP_SPPT',
               existing_type=mysql.VARCHAR(charset='utf8mb3', collation='utf8mb3_general_ci', length=15),
               type_=sqlmodel.sql.sqltypes.AutoString(length=45),
               existing_nullable=True)
    op.alter_column('sppt', 'RW_WP_SPPT',
               existing_type=mysql.VARCHAR(charset='utf8mb3', collation='utf8mb3_general_ci', length=2),
               type_=sqlmodel.sql.sqltypes.AutoString(length=6),
               existing_nullable=True)
    op.alter_column('sppt', 'RT_WP_SPPT',
               existing_type=mysql.VARCHAR(charset='utf8mb3', collation='utf8mb3_general_ci', length=3),
               type_=sqlmodel.sql.sqltypes.AutoString(length=9),
               existing_nullable=True)
    op.alter_column('sppt', 'KELURAHAN_WP_SPPT',
               existing_type=mysql.VARCHAR(charset='utf8mb3', collation='utf8mb3_general_ci', length=30),
               type_=sqlmodel.sql.sqltypes.AutoString(length=90),
               existing_nullable=True)
    op.alter_column('sppt', 'KOTA_WP_SPPT',
               existing_type=mysql.VARCHAR(charset='utf8mb3', collation='utf8mb3_general_ci', length=30),
               type_=sqlmodel.sql.sqltypes.AutoString(length=90),
               existing_nullable=True)
    op.alter_column('sppt', 'KD_POS_WP_SPPT',
               existing_type=mysql.VARCHAR(charset='utf8mb3', collation='utf8mb3_general_ci', length=5),
               type_=sqlmodel.sql.sqltypes.AutoString(length=15),
               existing_nullable=True)
    op.alter_column('sppt', 'NPWP_SPPT',
               existing_type=mysql.VARCHAR(charset='utf8mb3', collation='utf8mb3_general_ci', length=15),
               type_=sqlmodel.sql.sqltypes.AutoString(length=45),
               existing_nullable=True)
    op.alter_column('sppt', 'NO_PERSIL_SPPT',
               existing_type=mysql.VARCHAR(charset='utf8mb3', collation='utf8mb3_general_ci', length=5),
               type_=sqlmodel.sql.sqltypes.AutoString(length=15),
               existing_nullable=True)
    op.alter_column('sppt', 'KD_KLS_TANAH',
               existing_type=mysql.VARCHAR(charset='utf8mb3', collation='utf8mb3_general_ci', length=3),
               type_=sqlmodel.sql.sqltypes.AutoString(length=9),
               existing_nullable=True)
    op.alter_column('sppt', 'THN_AWAL_KLS_TANAH',
               existing_type=mysql.YEAR(),
               type_=sa.Integer(),
               existing_nullable=True,
               existing_server_default=sa.text("'2000'"))
    op.alter_column('sppt', 'KD_KLS_BNG',
               existing_type=mysql.VARCHAR(charset='utf8mb3', collation='utf8mb3_general_ci', length=3),
               type_=sqlmodel.sql.sqltypes.AutoString(length=9),
               existing_nullable=True)
    op.alter_column('sppt', 'THN_AWAL_KLS_BNG',
               existing_type=mysql.YEAR(),
               type_=sa.Integer(),
               existing_nullable=True,
               existing_server_default=sa.text("'2000'"))
    op.alter_column('sppt', 'LUAS_BUMI_SPPT',
               existing_type=mysql.BIGINT(),
               type_=sa.Integer(),
               nullable=True,
               existing_server_default=sa.text("'0'"))
    op.alter_column('sppt', 'LUAS_BNG_SPPT',
               existing_type=mysql.BIGINT(),
               type_=sa.Integer(),
               nullable=True,
               existing_server_default=sa.text("'0'"))
    op.alter_column('sppt', 'NJOP_BUMI_SPPT',
               existing_type=mysql.BIGINT(),
               type_=sa.Integer(),
               nullable=True,
               existing_server_default=sa.text("'0'"))
    op.alter_column('sppt', 'NJOP_BNG_SPPT',
               existing_type=mysql.BIGINT(),
               type_=sa.Integer(),
               nullable=True,
               existing_server_default=sa.text("'0'"))
    op.alter_column('sppt', 'NJOP_SPPT',
               existing_type=mysql.BIGINT(),
               type_=sa.Integer(),
               nullable=True,
               existing_server_default=sa.text("'0'"))
    op.alter_column('sppt', 'NJOPTKP_SPPT',
               existing_type=mysql.INTEGER(),
               nullable=True,
               existing_server_default=sa.text("'0'"))
    op.alter_column('sppt', 'NJKP_SPPT',
               existing_type=mysql.BIGINT(),
               type_=sa.Integer(),
               nullable=True,
               existing_server_default=sa.text("'0'"))
    op.alter_column('sppt', 'PBB_TERHUTANG_SPPT',
               existing_type=mysql.BIGINT(),
               type_=sa.Integer(),
               nullable=True,
               existing_server_default=sa.text("'0'"))
    op.alter_column('sppt', 'FAKTOR_PENGURANG_SPPT',
               existing_type=mysql.BIGINT(),
               type_=sa.Integer(),
               nullable=True,
               existing_server_default=sa.text("'0'"))
    op.alter_column('sppt', 'PBB_YG_HARUS_DIBAYAR_SPPT',
               existing_type=mysql.BIGINT(),
               type_=sa.Integer(),
               nullable=True,
               existing_server_default=sa.text("'0'"))
    op.alter_column('sppt', 'NIP_PENCETAK_SPPT',
               existing_type=mysql.VARCHAR(length=20),
               type_=sqlmodel.sql.sqltypes.AutoString(length=60),
               existing_nullable=True)
    op.drop_index('idx_sppt_join', table_name='sppt')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_sppt_join', 'sppt', ['KD_PROPINSI', 'KD_DATI2', 'KD_KECAMATAN', 'KD_KELURAHAN', 'KD_BLOK', 'NO_URUT', 'KD_JNS_OP'], unique=False)
    op.alter_column('sppt', 'NIP_PENCETAK_SPPT',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=60),
               type_=mysql.VARCHAR(length=20),
               existing_nullable=True)
    op.alter_column('sppt', 'PBB_YG_HARUS_DIBAYAR_SPPT',
               existing_type=sa.Integer(),
               type_=mysql.BIGINT(),
               nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('sppt', 'FAKTOR_PENGURANG_SPPT',
               existing_type=sa.Integer(),
               type_=mysql.BIGINT(),
               nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('sppt', 'PBB_TERHUTANG_SPPT',
               existing_type=sa.Integer(),
               type_=mysql.BIGINT(),
               nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('sppt', 'NJKP_SPPT',
               existing_type=sa.Integer(),
               type_=mysql.BIGINT(),
               nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('sppt', 'NJOPTKP_SPPT',
               existing_type=mysql.INTEGER(),
               nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('sppt', 'NJOP_SPPT',
               existing_type=sa.Integer(),
               type_=mysql.BIGINT(),
               nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('sppt', 'NJOP_BNG_SPPT',
               existing_type=sa.Integer(),
               type_=mysql.BIGINT(),
               nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('sppt', 'NJOP_BUMI_SPPT',
               existing_type=sa.Integer(),
               type_=mysql.BIGINT(),
               nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('sppt', 'LUAS_BNG_SPPT',
               existing_type=sa.Integer(),
               type_=mysql.BIGINT(),
               nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('sppt', 'LUAS_BUMI_SPPT',
               existing_type=sa.Integer(),
               type_=mysql.BIGINT(),
               nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('sppt', 'THN_AWAL_KLS_BNG',
               existing_type=sa.Integer(),
               type_=mysql.YEAR(),
               existing_nullable=True,
               existing_server_default=sa.text("'2000'"))
    op.alter_column('sppt', 'KD_KLS_BNG',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=9),
               type_=mysql.VARCHAR(charset='utf8mb3', collation='utf8mb3_general_ci', length=3),
               existing_nullable=True)
    op.alter_column('sppt', 'THN_AWAL_KLS_TANAH',
               existing_type=sa.Integer(),
               type_=mysql.YEAR(),
               existing_nullable=True,
               existing_server_default=sa.text("'2000'"))
    op.alter_column('sppt', 'KD_KLS_TANAH',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=9),
               type_=mysql.VARCHAR(charset='utf8mb3', collation='utf8mb3_general_ci', length=3),
               existing_nullable=True)
    op.alter_column('sppt', 'NO_PERSIL_SPPT',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=15),
               type_=mysql.VARCHAR(charset='utf8mb3', collation='utf8mb3_general_ci', length=5),
               existing_nullable=True)
    op.alter_column('sppt', 'NPWP_SPPT',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=45),
               type_=mysql.VARCHAR(charset='utf8mb3', collation='utf8mb3_general_ci', length=15),
               existing_nullable=True)
    op.alter_column('sppt', 'KD_POS_WP_SPPT',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=15),
               type_=mysql.VARCHAR(charset='utf8mb3', collation='utf8mb3_general_ci', length=5),
               existing_nullable=True)
    op.alter_column('sppt', 'KOTA_WP_SPPT',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=90),
               type_=mysql.VARCHAR(charset='utf8mb3', collation='utf8mb3_general_ci', length=30),
               existing_nullable=True)
    op.alter_column('sppt', 'KELURAHAN_WP_SPPT',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=90),
               type_=mysql.VARCHAR(charset='utf8mb3', collation='utf8mb3_general_ci', length=30),
               existing_nullable=True)
    op.alter_column('sppt', 'RT_WP_SPPT',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=9),
               type_=mysql.VARCHAR(charset='utf8mb3', collation='utf8mb3_general_ci', length=3),
               existing_nullable=True)
    op.alter_column('sppt', 'RW_WP_SPPT',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=6),
               type_=mysql.VARCHAR(charset='utf8mb3', collation='utf8mb3_general_ci', length=2),
               existing_nullable=True)
    op.alter_column('sppt', 'BLOK_KAV_NO_WP_SPPT',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=45),
               type_=mysql.VARCHAR(charset='utf8mb3', collation='utf8mb3_general_ci', length=15),
               existing_nullable=True)
    op.alter_column('sppt', 'JLN_WP_SPPT',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=90),
               type_=mysql.VARCHAR(charset='utf8mb3', collation='utf8mb3_general_ci', length=30),
               existing_nullable=True)
    op.alter_column('sppt', 'NM_WP_SPPT',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=90),
               type_=mysql.VARCHAR(charset='utf8mb3', collation='utf8mb3_general_ci', length=30),
               existing_nullable=True)
    op.alter_column('sppt', 'KD_TP',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=6),
               type_=mysql.VARCHAR(charset='utf8mb3', collation='utf8mb3_general_ci', length=2),
               existing_nullable=True)
    op.alter_column('sppt', 'KD_BANK_PERSEPSI',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=6),
               type_=mysql.VARCHAR(charset='utf8mb3', collation='utf8mb3_general_ci', length=2),
               existing_nullable=True)
    op.alter_column('sppt', 'KD_BANK_TUNGGAL',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=6),
               type_=mysql.VARCHAR(charset='utf8mb3', collation='utf8mb3_general_ci', length=2),
               existing_nullable=True)
    op.alter_column('sppt', 'KD_KPPBB_BANK',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=6),
               type_=mysql.VARCHAR(charset='utf8mb3', collation='utf8mb3_general_ci', length=2),
               existing_nullable=True)
    op.alter_column('sppt', 'KD_KANWIL_BANK',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=6),
               type_=mysql.VARCHAR(charset='utf8mb3', collation='utf8mb3_general_ci', length=2),
               existing_nullable=True)
    op.alter_column('sppt', 'SIKLUS_SPPT',
               existing_type=sa.Integer(),
               type_=mysql.TINYINT(),
               existing_nullable=True)
    op.alter_column('sppt', 'THN_PAJAK_SPPT',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=12),
               type_=mysql.VARCHAR(length=4),
               existing_nullable=False)
    op.alter_column('sppt', 'KD_JNS_OP',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=3),
               type_=mysql.VARCHAR(charset='utf8mb3', collation='utf8mb3_general_ci', length=1),
               existing_nullable=False)
    op.alter_column('sppt', 'NO_URUT',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=12),
               type_=mysql.VARCHAR(charset='utf8mb3', collation='utf8mb3_general_ci', length=4),
               existing_nullable=False)
    op.alter_column('sppt', 'KD_BLOK',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=9),
               type_=mysql.VARCHAR(charset='utf8mb3', collation='utf8mb3_general_ci', length=3),
               existing_nullable=False)
    op.alter_column('sppt', 'KD_KELURAHAN',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=9),
               type_=mysql.VARCHAR(charset='utf8mb3', collation='utf8mb3_general_ci', length=3),
               existing_nullable=False)
    op.alter_column('sppt', 'KD_KECAMATAN',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=9),
               type_=mysql.VARCHAR(charset='utf8mb3', collation='utf8mb3_general_ci', length=3),
               existing_nullable=False)
    op.alter_column('sppt', 'KD_DATI2',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=6),
               type_=mysql.VARCHAR(charset='utf8mb3', collation='utf8mb3_general_ci', length=2),
               existing_nullable=False)
    op.alter_column('sppt', 'KD_PROPINSI',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=6),
               type_=mysql.VARCHAR(charset='utf8mb3', collation='utf8mb3_general_ci', length=2),
               existing_nullable=False)
    op.alter_column('spop', 'NO_PERSIL',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=15),
               type_=mysql.VARCHAR(length=5),
               existing_nullable=True)
    op.alter_column('spop', 'NIP_PEMERIKSA_OP',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=60),
               type_=mysql.VARCHAR(length=20),
               existing_nullable=True)
    op.alter_column('spop', 'NM_PEMERIKSAAN_OP',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=90),
               type_=mysql.VARCHAR(length=30),
               existing_nullable=True)
    op.alter_column('spop', 'TGL_PEMERIKSAAN_OP',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('spop', 'NIP_PENDATA',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=60),
               type_=mysql.VARCHAR(length=20),
               existing_nullable=True)
    op.alter_column('spop', 'NM_PENDATAAN_OP',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=90),
               type_=mysql.VARCHAR(length=30),
               existing_nullable=True)
    op.alter_column('spop', 'TGL_PENDATAAN_OP',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('spop', 'NILAI_SISTEM_BUMI',
               existing_type=sa.Integer(),
               type_=mysql.BIGINT(),
               nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('spop', 'JNS_BUMI',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=3),
               type_=mysql.VARCHAR(charset='utf8mb3', collation='utf8mb3_general_ci', length=1),
               nullable=False)
    op.alter_column('spop', 'KD_ZNT',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=6),
               type_=mysql.VARCHAR(charset='utf8mb3', collation='utf8mb3_general_ci', length=2),
               existing_nullable=True)
    op.alter_column('spop', 'LUAS_BUMI',
               existing_type=sa.Integer(),
               type_=mysql.BIGINT(),
               nullable=False)
    op.alter_column('spop', 'KD_STATUS_WP',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=3),
               type_=mysql.VARCHAR(charset='utf8mb3', collation='utf8mb3_general_ci', length=1),
               nullable=False)
    op.alter_column('spop', 'RT_OP',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=9),
               type_=mysql.VARCHAR(charset='utf8mb3', collation='utf8mb3_general_ci', length=3),
               existing_nullable=True)
    op.alter_column('spop', 'RW_OP',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=6),
               type_=mysql.VARCHAR(charset='utf8mb3', collation='utf8mb3_general_ci', length=2),
               existing_nullable=True)
    op.alter_column('spop', 'KELURAHAN_OP',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=90),
               type_=mysql.VARCHAR(charset='utf8mb3', collation='utf8mb3_general_ci', length=30),
               existing_nullable=True)
    op.alter_column('spop', 'BLOK_KAV_NO_OP',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=45),
               type_=mysql.VARCHAR(charset='utf8mb3', collation='utf8mb3_general_ci', length=15),
               existing_nullable=True)
    op.alter_column('spop', 'JALAN_OP',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=90),
               type_=mysql.VARCHAR(charset='utf8mb3', collation='utf8mb3_general_ci', length=30),
               nullable=False)
    op.alter_column('spop', 'NO_SPPT_LAMA',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=54),
               type_=mysql.VARCHAR(charset='utf8mb3', collation='utf8mb3_general_ci', length=18),
               existing_nullable=True)
    op.alter_column('spop', 'KD_JNS_OP_ASAL',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=3),
               type_=mysql.VARCHAR(charset='utf8mb3', collation='utf8mb3_general_ci', length=1),
               existing_nullable=True)
    op.alter_column('spop', 'NO_URUT_ASAL',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=12),
               type_=mysql.VARCHAR(charset='utf8mb3', collation='utf8mb3_general_ci', length=4),
               existing_nullable=True)
    op.alter_column('spop', 'KD_BLOK_ASAL',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=9),
               type_=mysql.VARCHAR(charset='utf8mb3', collation='utf8mb3_general_ci', length=3),
               existing_nullable=True)
    op.alter_column('spop', 'KD_KELURAHAN_ASAL',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=9),
               type_=mysql.VARCHAR(charset='utf8mb3', collation='utf8mb3_general_ci', length=3),
               existing_nullable=True)
    op.alter_column('spop', 'KD_KECAMATAN_ASAL',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=9),
               type_=mysql.VARCHAR(charset='utf8mb3', collation='utf8mb3_general_ci', length=3),
               existing_nullable=True)
    op.alter_column('spop', 'KD_DATI2_ASAL',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=6),
               type_=mysql.VARCHAR(charset='utf8mb3', collation='utf8mb3_general_ci', length=2),
               existing_nullable=True)
    op.alter_column('spop', 'KD_PROPINSI_ASAL',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=6),
               type_=mysql.VARCHAR(charset='utf8mb3', collation='utf8mb3_general_ci', length=2),
               existing_nullable=True)
    op.alter_column('spop', 'KD_JNS_OP_BERSAMA',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=3),
               type_=mysql.VARCHAR(charset='utf8mb3', collation='utf8mb3_general_ci', length=1),
               existing_nullable=True)
    op.alter_column('spop', 'NO_URUT_BERSAMA',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=12),
               type_=mysql.VARCHAR(charset='utf8mb3', collation='utf8mb3_general_ci', length=4),
               existing_nullable=True)
    op.alter_column('spop', 'KD_BLOK_BERSAMA',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=9),
               type_=mysql.VARCHAR(charset='utf8mb3', collation='utf8mb3_general_ci', length=3),
               existing_nullable=True)
    op.alter_column('spop', 'KD_KELURAHAN_BERSAMA',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=9),
               type_=mysql.VARCHAR(charset='utf8mb3', collation='utf8mb3_general_ci', length=3),
               existing_nullable=True)
    op.alter_column('spop', 'KD_KECAMATAN_BERSAMA',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=9),
               type_=mysql.VARCHAR(charset='utf8mb3', collation='utf8mb3_general_ci', length=3),
               existing_nullable=True)
    op.alter_column('spop', 'KD_DATI2_BERSAMA',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=6),
               type_=mysql.VARCHAR(charset='utf8mb3', collation='utf8mb3_general_ci', length=2),
               existing_nullable=True)
    op.alter_column('spop', 'KD_PROPINSI_BERSAMA',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=6),
               type_=mysql.VARCHAR(charset='utf8mb3', collation='utf8mb3_general_ci', length=2),
               existing_nullable=True)
    op.alter_column('spop', 'JNS_TRANSAKSI_OP',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=3),
               type_=mysql.VARCHAR(charset='utf8mb3', collation='utf8mb3_general_ci', length=1),
               nullable=False)
    op.alter_column('spop', 'NO_FORMULIR_SPOP',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=33),
               type_=mysql.VARCHAR(charset='utf8mb3', collation='utf8mb3_general_ci', length=11),
               existing_nullable=True)
    op.alter_column('spop', 'SUBJEK_PAJAK_ID',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=90),
               type_=mysql.VARCHAR(charset='utf8mb3', collation='utf8mb3_general_ci', length=30),
               nullable=False)
    op.alter_column('spop', 'KD_JNS_OP',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=3),
               type_=mysql.VARCHAR(charset='utf8mb3', collation='utf8mb3_general_ci', length=1),
               existing_nullable=False)
    op.alter_column('spop', 'NO_URUT',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=12),
               type_=mysql.VARCHAR(charset='utf8mb3', collation='utf8mb3_general_ci', length=4),
               existing_nullable=False)
    op.alter_column('spop', 'KD_BLOK',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=9),
               type_=mysql.VARCHAR(charset='utf8mb3', collation='utf8mb3_general_ci', length=3),
               existing_nullable=False)
    op.alter_column('spop', 'KD_KELURAHAN',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=9),
               type_=mysql.VARCHAR(charset='utf8mb3', collation='utf8mb3_general_ci', length=3),
               existing_nullable=False)
    op.alter_column('spop', 'KD_KECAMATAN',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=9),
               type_=mysql.VARCHAR(charset='utf8mb3', collation='utf8mb3_general_ci', length=3),
               existing_nullable=False)
    op.alter_column('spop', 'KD_DATI2',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=6),
               type_=mysql.VARCHAR(charset='utf8mb3', collation='utf8mb3_general_ci', length=2),
               existing_nullable=False)
    op.alter_column('spop', 'KD_PROPINSI',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=6),
               type_=mysql.VARCHAR(charset='utf8mb3', collation='utf8mb3_general_ci', length=2),
               existing_nullable=False)
    op.drop_column('ipbb_user', 'is_admin')
    op.alter_column('dat_subjek_pajak', 'EMAIL_WP',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=150),
               type_=mysql.VARCHAR(length=50),
               existing_nullable=True)
    op.alter_column('dat_subjek_pajak', 'STATUS_PEKERJAAN_WP',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=3),
               type_=mysql.VARCHAR(charset='utf8mb3', collation='utf8mb3_general_ci', length=1),
               nullable=False)
    op.alter_column('dat_subjek_pajak', 'NPWP',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=45),
               type_=mysql.VARCHAR(charset='utf8mb3', collation='utf8mb3_general_ci', length=15),
               existing_nullable=True)
    op.alter_column('dat_subjek_pajak', 'TELP_WP',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=60),
               type_=mysql.VARCHAR(charset='utf8mb3', collation='utf8mb3_general_ci', length=20),
               existing_nullable=True)
    op.alter_column('dat_subjek_pajak', 'KD_POS_WP',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=15),
               type_=mysql.VARCHAR(charset='utf8mb3', collation='utf8mb3_general_ci', length=5),
               existing_nullable=True)
    op.alter_column('dat_subjek_pajak', 'KOTA_WP',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=90),
               type_=mysql.VARCHAR(charset='utf8mb3', collation='utf8mb3_general_ci', length=30),
               existing_nullable=True)
    op.alter_column('dat_subjek_pajak', 'KELURAHAN_WP',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=90),
               type_=mysql.VARCHAR(charset='utf8mb3', collation='utf8mb3_general_ci', length=30),
               existing_nullable=True)
    op.alter_column('dat_subjek_pajak', 'RT_WP',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=9),
               type_=mysql.VARCHAR(charset='utf8mb3', collation='utf8mb3_general_ci', length=3),
               existing_nullable=True)
    op.alter_column('dat_subjek_pajak', 'RW_WP',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=6),
               type_=mysql.VARCHAR(charset='utf8mb3', collation='utf8mb3_general_ci', length=2),
               existing_nullable=True)
    op.alter_column('dat_subjek_pajak', 'BLOK_KAV_NO_WP',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=45),
               type_=mysql.VARCHAR(charset='utf8mb3', collation='utf8mb3_general_ci', length=15),
               existing_nullable=True)
    op.alter_column('dat_subjek_pajak', 'JALAN_WP',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=90),
               type_=mysql.VARCHAR(charset='utf8mb3', collation='utf8mb3_general_ci', length=30),
               nullable=False)
    op.alter_column('dat_subjek_pajak', 'NM_WP',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=90),
               type_=mysql.VARCHAR(charset='utf8mb3', collation='utf8mb3_general_ci', length=30),
               nullable=False)
    op.alter_column('dat_subjek_pajak', 'SUBJEK_PAJAK_ID',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=90),
               type_=mysql.VARCHAR(charset='utf8mb3', collation='utf8mb3_general_ci', length=30),
               existing_nullable=False)
    op.create_table('dat_op_bangunan',
    sa.Column('KD_PROPINSI', mysql.CHAR(length=2), nullable=False),
    sa.Column('KD_DATI2', mysql.CHAR(length=2), nullable=False),
    sa.Column('KD_KECAMATAN', mysql.CHAR(length=3), nullable=False),
    sa.Column('KD_KELURAHAN', mysql.CHAR(length=3), nullable=False),
    sa.Column('KD_BLOK', mysql.CHAR(length=3), nullable=False),
    sa.Column('NO_URUT', mysql.CHAR(length=4), nullable=False),
    sa.Column('KD_JNS_OP', mysql.CHAR(length=1), nullable=False),
    sa.Column('NO_BNG', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('KD_JPB', mysql.CHAR(length=2), nullable=True),
    sa.Column('NO_FORMULIR_LSPOP', mysql.CHAR(length=11), nullable=True),
    sa.Column('THN_DIBANGUN_BNG', mysql.CHAR(length=4), server_default=sa.text("'0'"), nullable=False),
    sa.Column('THN_RENOVASI_BNG', mysql.CHAR(length=4), nullable=True),
    sa.Column('LUAS_BNG', mysql.BIGINT(), server_default=sa.text("'0'"), autoincrement=False, nullable=False),
    sa.Column('JML_LANTAI_BNG', mysql.INTEGER(), server_default=sa.text("'1'"), autoincrement=False, nullable=False),
    sa.Column('KONDISI_BNG', mysql.CHAR(length=1), nullable=True),
    sa.Column('JNS_KONSTRUKSI_BNG', mysql.CHAR(length=1), nullable=True),
    sa.Column('JNS_ATAP_BNG', mysql.CHAR(length=1), nullable=True),
    sa.Column('KD_DINDING', mysql.CHAR(length=1), nullable=True),
    sa.Column('KD_LANTAI', mysql.CHAR(length=1), nullable=True),
    sa.Column('KD_LANGIT_LANGIT', mysql.CHAR(length=1), nullable=True),
    sa.Column('NILAI_SISTEM_BNG', mysql.BIGINT(), server_default=sa.text("'0'"), autoincrement=False, nullable=False),
    sa.Column('JNS_TRANSAKSI_BNG', mysql.CHAR(length=1), nullable=True),
    sa.Column('TGL_PENDATAAN_BNG', mysql.DATETIME(), nullable=True),
    sa.Column('NIP_PENDATA_BNG', mysql.CHAR(length=30), nullable=True),
    sa.Column('TGL_PEMERIKSAAN_BNG', mysql.DATETIME(), nullable=True),
    sa.Column('NIP_PEMERIKSA_BNG', mysql.CHAR(length=30), nullable=True),
    sa.Column('TGL_PEREKAMAN_BNG', mysql.DATETIME(), nullable=True),
    sa.Column('NIP_PEREKAM_BNG', mysql.CHAR(length=30), nullable=True),
    sa.Column('TGL_KUNJUNGAN_KEMBALI', sa.DATE(), nullable=True),
    sa.Column('NILAI_INDIVIDU', mysql.BIGINT(), server_default=sa.text("'0'"), autoincrement=False, nullable=False),
    sa.Column('AKTIF', mysql.TINYINT(display_width=1), server_default=sa.text("'1'"), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('KD_PROPINSI', 'KD_DATI2', 'KD_KECAMATAN', 'KD_KELURAHAN', 'KD_BLOK', 'NO_URUT', 'KD_JNS_OP', 'NO_BNG'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
