/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import {
  z as zod
} from 'zod';


/**
 * @summary Get Dashboard Stats
 */
export const dashboardGetDashboardStatsResponse = zod.any()

