/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import {
  z as zod
} from 'zod';


/**
 * Get current user's profile data from dat_subjek_pajak based on email
 * @summary Get My Profile
 */
export const profileGetMyProfileResponse = zod.any()

