/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import useSwr from 'swr';
import type {
  Key,
  SWRConfiguration
} from 'swr';

import useSWRMutation from 'swr/mutation';
import type {
  SWRMutationConfiguration
} from 'swr/mutation';

import type {
  ErrorResponse,
  ExistsResponse,
  HTTPValidationError,
  NopRequest,
  OpGetAllSpopParams,
  SpopPaginatedResponse,
  SpptResponse,
  SpptYearsResponse,
  VerifikasiRequest
} from '../../models';

import { clientFetcher } from '../../../../lib/orval/mutator';
import type { ErrorType , BodyType } from '../../../../lib/orval/mutator';


  
  type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];


  
/**
 * @summary Verifikasi
 */
export const opVerifikasi = (
    verifikasiRequest: BodyType<VerifikasiRequest>,
 options?: SecondParameter<typeof clientFetcher>) => {
    return clientFetcher<ExistsResponse>(
    {url: `/op/verifikasi`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: verifikasiRequest
    },
    options);
  }



export const getOpVerifikasiMutationFetcher = ( options?: SecondParameter<typeof clientFetcher>) => {
  return (_: Key, { arg }: { arg: VerifikasiRequest }): Promise<ExistsResponse> => {
    return opVerifikasi(arg, options);
  }
}
export const getOpVerifikasiMutationKey = () => [`/op/verifikasi`] as const;

export type OpVerifikasiMutationResult = NonNullable<Awaited<ReturnType<typeof opVerifikasi>>>
export type OpVerifikasiMutationError = ErrorType<HTTPValidationError>

/**
 * @summary Verifikasi
 */
export const useOpVerifikasi = <TError = ErrorType<HTTPValidationError>>(
   options?: { swr?:SWRMutationConfiguration<Awaited<ReturnType<typeof opVerifikasi>>, TError, Key, VerifikasiRequest, Awaited<ReturnType<typeof opVerifikasi>>> & { swrKey?: string }, request?: SecondParameter<typeof clientFetcher>}
) => {

  const {swr: swrOptions, request: requestOptions} = options ?? {}

  const swrKey = swrOptions?.swrKey ?? getOpVerifikasiMutationKey();
  const swrFn = getOpVerifikasiMutationFetcher(requestOptions);

  const query = useSWRMutation(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
/**
 * List all objects (SPOP) for the current user. Use this endpoint to select an object (NOP) before choosing a year.
 * @summary Get All Spop
 */
export const opGetAllSpop = (
    params?: OpGetAllSpopParams,
 options?: SecondParameter<typeof clientFetcher>) => {
    return clientFetcher<SpopPaginatedResponse>(
    {url: `/op/spop`, method: 'GET',
        params
    },
    options);
  }



export const getOpGetAllSpopKey = (params?: OpGetAllSpopParams,) => [`/op/spop`, ...(params ? [params]: [])] as const;

export type OpGetAllSpopQueryResult = NonNullable<Awaited<ReturnType<typeof opGetAllSpop>>>
export type OpGetAllSpopQueryError = ErrorType<HTTPValidationError>

/**
 * @summary Get All Spop
 */
export const useOpGetAllSpop = <TError = ErrorType<HTTPValidationError>>(
  params?: OpGetAllSpopParams, options?: { swr?:SWRConfiguration<Awaited<ReturnType<typeof opGetAllSpop>>, TError> & { swrKey?: Key, enabled?: boolean }, request?: SecondParameter<typeof clientFetcher> }
) => {
  const {swr: swrOptions, request: requestOptions} = options ?? {}

  const isEnabled = swrOptions?.enabled !== false
  const swrKey = swrOptions?.swrKey ?? (() => isEnabled ? getOpGetAllSpopKey(params) : null);
  const swrFn = () => opGetAllSpop(params, requestOptions)

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
/**
 * @summary Get Sppt
 */
export const opGetSppt = (
    
 options?: SecondParameter<typeof clientFetcher>) => {
    return clientFetcher<ErrorResponse>(
    {url: `/op/`, method: 'GET'
    },
    options);
  }



export const getOpGetSpptKey = () => [`/op/`] as const;

export type OpGetSpptQueryResult = NonNullable<Awaited<ReturnType<typeof opGetSppt>>>
export type OpGetSpptQueryError = ErrorType<unknown>

/**
 * @summary Get Sppt
 */
export const useOpGetSppt = <TError = ErrorType<unknown>>(
   options?: { swr?:SWRConfiguration<Awaited<ReturnType<typeof opGetSppt>>, TError> & { swrKey?: Key, enabled?: boolean }, request?: SecondParameter<typeof clientFetcher> }
) => {
  const {swr: swrOptions, request: requestOptions} = options ?? {}

  const isEnabled = swrOptions?.enabled !== false
  const swrKey = swrOptions?.swrKey ?? (() => isEnabled ? getOpGetSpptKey() : null);
  const swrFn = () => opGetSppt(requestOptions)

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
/**
 * Get available SPPT years for a specific object (NOP). Pass the NOP as JSON body.
 * @summary Get Sppt Years
 */
export const opGetSpptYears = (
    nopRequest: BodyType<NopRequest>,
 options?: SecondParameter<typeof clientFetcher>) => {
    return clientFetcher<SpptYearsResponse>(
    {url: `/op/sppt/years`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: nopRequest
    },
    options);
  }



export const getOpGetSpptYearsMutationFetcher = ( options?: SecondParameter<typeof clientFetcher>) => {
  return (_: Key, { arg }: { arg: NopRequest }): Promise<SpptYearsResponse> => {
    return opGetSpptYears(arg, options);
  }
}
export const getOpGetSpptYearsMutationKey = () => [`/op/sppt/years`] as const;

export type OpGetSpptYearsMutationResult = NonNullable<Awaited<ReturnType<typeof opGetSpptYears>>>
export type OpGetSpptYearsMutationError = ErrorType<HTTPValidationError>

/**
 * @summary Get Sppt Years
 */
export const useOpGetSpptYears = <TError = ErrorType<HTTPValidationError>>(
   options?: { swr?:SWRMutationConfiguration<Awaited<ReturnType<typeof opGetSpptYears>>, TError, Key, NopRequest, Awaited<ReturnType<typeof opGetSpptYears>>> & { swrKey?: string }, request?: SecondParameter<typeof clientFetcher>}
) => {

  const {swr: swrOptions, request: requestOptions} = options ?? {}

  const swrKey = swrOptions?.swrKey ?? getOpGetSpptYearsMutationKey();
  const swrFn = getOpGetSpptYearsMutationFetcher(requestOptions);

  const query = useSWRMutation(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
/**
 * Get detailed SPPT data for a specific property (object) and year. Use after selecting object and year. NOP is a single string.
 * @summary Get Sppt Detail
 */
export const opGetSpptDetail = (
    year: string,
    nop: string,
 options?: SecondParameter<typeof clientFetcher>) => {
    return clientFetcher<SpptResponse>(
    {url: `/op/sppt/${year}/${nop}`, method: 'GET'
    },
    options);
  }



export const getOpGetSpptDetailKey = (year: string,
    nop: string,) => [`/op/sppt/${year}/${nop}`] as const;

export type OpGetSpptDetailQueryResult = NonNullable<Awaited<ReturnType<typeof opGetSpptDetail>>>
export type OpGetSpptDetailQueryError = ErrorType<HTTPValidationError>

/**
 * @summary Get Sppt Detail
 */
export const useOpGetSpptDetail = <TError = ErrorType<HTTPValidationError>>(
  year: string,
    nop: string, options?: { swr?:SWRConfiguration<Awaited<ReturnType<typeof opGetSpptDetail>>, TError> & { swrKey?: Key, enabled?: boolean }, request?: SecondParameter<typeof clientFetcher> }
) => {
  const {swr: swrOptions, request: requestOptions} = options ?? {}

  const isEnabled = swrOptions?.enabled !== false && !!(year && nop)
  const swrKey = swrOptions?.swrKey ?? (() => isEnabled ? getOpGetSpptDetailKey(year,nop) : null);
  const swrFn = () => opGetSpptDetail(year,nop, requestOptions)

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
