/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import {
  z as zod
} from 'zod';


/**
 * @summary Verifikasi
 */
export const opVerifikasiBody = zod.object({
  "SUBJEK_PAJAK_ID": zod.string(),
  "NM_WP": zod.string(),
  "KD_PROPINSI": zod.string(),
  "KD_DATI2": zod.string(),
  "KD_KECAMATAN": zod.string(),
  "KD_KELURAHAN": zod.string(),
  "KD_BLOK": zod.string(),
  "NO_URUT": zod.string(),
  "KD_JNS_OP": zod.string(),
  "TELP_WP": zod.string()
})

export const opVerifikasiResponse = zod.object({
  "exists": zod.boolean()
})

/**
 * List all objects (SPOP) for the current user. Use this endpoint to select an object (NOP) before choosing a year.
 * @summary Get All Spop
 */
export const opGetAllSpopQueryPageDefault = 1;export const opGetAllSpopQueryPerPageDefault = 10;
export const opGetAllSpopQueryPerPageMax = 100;
export const opGetAllSpopQuerySortByDefault = "KD_PROPINSI";export const opGetAllSpopQuerySortOrderDefault = "asc";

export const opGetAllSpopQueryParams = zod.object({
  "search": zod.string().or(zod.null()).optional().describe('Search by NM_WP'),
  "page": zod.number().min(1).default(opGetAllSpopQueryPageDefault),
  "per_page": zod.number().min(1).max(opGetAllSpopQueryPerPageMax).default(opGetAllSpopQueryPerPageDefault),
  "sort_by": zod.enum(['KD_PROPINSI', 'JALAN_OP', 'LUAS_BUMI']).or(zod.null()).default(opGetAllSpopQuerySortByDefault),
  "sort_order": zod.enum(['asc', 'desc']).or(zod.null()).default(opGetAllSpopQuerySortOrderDefault)
})

export const opGetAllSpopResponse = zod.object({
  "data": zod.array(zod.object({
  "NM_WP": zod.string().or(zod.null()).optional(),
  "JNS_TRANSAKSI_OP": zod.string(),
  "KD_PROPINSI_ASAL": zod.string().or(zod.null()).optional(),
  "JALAN_OP": zod.string().or(zod.null()).optional(),
  "JNS_BUMI": zod.string().or(zod.null()).optional(),
  "NIP_PEMERIKSA_OP": zod.string().or(zod.null()).optional(),
  "KD_PROPINSI_BERSAMA": zod.string().or(zod.null()).optional(),
  "KD_DATI2_ASAL": zod.string().or(zod.null()).optional(),
  "BLOK_KAV_NO_OP": zod.string().or(zod.null()).optional(),
  "NILAI_SISTEM_BUMI": zod.number(),
  "NO_PERSIL": zod.string().or(zod.null()),
  "KD_BLOK": zod.string(),
  "KD_DATI2_BERSAMA": zod.string().or(zod.null()).optional(),
  "KD_KECAMATAN_ASAL": zod.string().or(zod.null()).optional(),
  "KELURAHAN_OP": zod.string().or(zod.null()).optional(),
  "TGL_PENDATAAN_OP": zod.string().date(),
  "KD_DATI2": zod.string(),
  "KD_KECAMATAN_BERSAMA": zod.string().or(zod.null()).optional(),
  "KD_KELURAHAN_ASAL": zod.string().or(zod.null()).optional(),
  "RW_OP": zod.string().or(zod.null()).optional(),
  "NM_PENDATAAN_OP": zod.string().or(zod.null()).optional(),
  "NO_URUT": zod.string(),
  "KD_KELURAHAN_BERSAMA": zod.string().or(zod.null()).optional(),
  "KD_BLOK_ASAL": zod.string().or(zod.null()).optional(),
  "RT_OP": zod.string().or(zod.null()).optional(),
  "KD_KELURAHAN": zod.string(),
  "KD_JNS_OP": zod.string(),
  "KD_BLOK_BERSAMA": zod.string().or(zod.null()).optional(),
  "NO_URUT_ASAL": zod.string().or(zod.null()).optional(),
  "KD_STATUS_WP": zod.string().or(zod.null()).optional(),
  "NIP_PENDATA": zod.string().or(zod.null()).optional(),
  "KD_PROPINSI": zod.string(),
  "KD_KECAMATAN": zod.string(),
  "SUBJEK_PAJAK_ID": zod.string(),
  "NO_URUT_BERSAMA": zod.string().or(zod.null()).optional(),
  "KD_JNS_OP_ASAL": zod.string().or(zod.null()).optional(),
  "LUAS_BUMI": zod.number(),
  "TGL_PEMERIKSAAN_OP": zod.string().date(),
  "NO_FORMULIR_SPOP": zod.string().or(zod.null()).optional(),
  "KD_JNS_OP_BERSAMA": zod.string().or(zod.null()).optional(),
  "NO_SPPT_LAMA": zod.string().or(zod.null()).optional(),
  "KD_ZNT": zod.string().or(zod.null()).optional(),
  "NM_PEMERIKSAAN_OP": zod.string().or(zod.null()).optional()
})),
  "meta": zod.object({
  "page": zod.number(),
  "per_page": zod.number(),
  "total": zod.number(),
  "total_pages": zod.number()
})
})

/**
 * @summary Get Sppt
 */
export const opGetSpptResponse = zod.object({
  "detail": zod.object({
  "code": zod.string(),
  "msg": zod.string()
})
})

/**
 * Get available SPPT years for a specific object (NOP). Pass the NOP as JSON body.
 * @summary Get Sppt Years
 */
export const opGetSpptYearsBody = zod.object({
  "nop": zod.string()
})

export const opGetSpptYearsResponse = zod.object({
  "available_years": zod.array(zod.object({
  "THN_PAJAK_SPPT": zod.string(),
  "count": zod.number()
}))
})

/**
 * Get detailed SPPT data for a specific property (object) and year. Use after selecting object and year. NOP is a single string.
 * @summary Get Sppt Detail
 */
export const opGetSpptDetailParams = zod.object({
  "year": zod.string(),
  "nop": zod.string()
})

export const opGetSpptDetailResponse = zod.object({
  "KD_PROPINSI": zod.string(),
  "KD_DATI2": zod.string(),
  "KD_KECAMATAN": zod.string(),
  "KD_KELURAHAN": zod.string(),
  "KD_BLOK": zod.string(),
  "NO_URUT": zod.string(),
  "KD_JNS_OP": zod.string(),
  "THN_PAJAK_SPPT": zod.string(),
  "NM_WP_SPPT": zod.string().or(zod.null()).optional(),
  "JLN_WP_SPPT": zod.string().or(zod.null()).optional(),
  "BLOK_KAV_NO_WP_SPPT": zod.string().or(zod.null()).optional(),
  "RW_WP_SPPT": zod.string().or(zod.null()).optional(),
  "RT_WP_SPPT": zod.string().or(zod.null()).optional(),
  "KELURAHAN_WP_SPPT": zod.string().or(zod.null()).optional(),
  "KOTA_WP_SPPT": zod.string().or(zod.null()).optional(),
  "KD_POS_WP_SPPT": zod.string().or(zod.null()).optional(),
  "NPWP_SPPT": zod.string().or(zod.null()).optional(),
  "TGL_JATUH_TEMPO_SPPT": zod.string().date().or(zod.null()).optional(),
  "LUAS_BUMI_SPPT": zod.number().or(zod.null()).optional(),
  "LUAS_BNG_SPPT": zod.number().or(zod.null()).optional(),
  "NJOP_BUMI_SPPT": zod.number().or(zod.null()).optional(),
  "NJOP_BNG_SPPT": zod.number().or(zod.null()).optional(),
  "NJOP_SPPT": zod.number().or(zod.null()).optional(),
  "NJOPTKP_SPPT": zod.number().or(zod.null()).optional(),
  "NJKP_SPPT": zod.number().or(zod.null()).optional(),
  "PBB_TERHUTANG_SPPT": zod.number().or(zod.null()).optional(),
  "PBB_YG_HARUS_DIBAYAR_SPPT": zod.number().or(zod.null()).optional(),
  "STATUS_PEMBAYARAN_SPPT": zod.boolean().or(zod.null()).optional(),
  "STATUS_TAGIHAN_SPPT": zod.boolean().or(zod.null()).optional(),
  "TGL_TERBIT_SPPT": zod.string().datetime({}).or(zod.null()).optional()
})

